"use strict";

// BH
const BH = [
  {
    "name" : "Moohoarrgh, the Perpetuator of Heroes",
    "category" : "Characters",
    "sticksandstones" : 0,
    "bigrocks" : 0,
  },
  {
    "name" : "Ghaa, THE Quiet Muzzle",
    "category" : "Characters",
    "sticksandstones" : 0,
    "bigrocks" : 0,
  },
  {
    "name" : "Wildhorn Lord",
    "category" : "Characters",
    "sticksandstones" : 0,
    "bigrocks" : 0,
  },
  {
    "name" : "Wildhorn Chieftain",
    "category" : "Characters",
    "sticksandstones" : 0,
    "bigrocks" : 0,
  },
  {
    "name" : "Soothsayer",
    "category" : "Characters",
    "sticksandstones" : 0,
    "bigrocks" : 0,
  },
  {
    "name" : "Centaur Chieftain",
    "category" : "Characters",
    "sticksandstones" : 0,
    "bigrocks" : 0,
  },
  {
    "name" : "Minotaur Warlord",
    "category" : "Characters",
    "sticksandstones" : 0,
    "bigrocks" : 0,
  },
  {
    "name" : "Minotaur Chieftain",
    "category" : "Characters",
    "sticksandstones" : 0,
    "bigrocks" : 0,
  },
  {
    "name" : "Wildhorn Herd",
    "category" : "Core",
    "sticksandstones" : 0,
    "bigrocks" : 0,
    "min" : 15,
    "max" : 50,
  },
  {
    "name" : "Mongrel Herd",
    "category" : "Core",
    "sticksandstones" : 0,
    "bigrocks" : 0,
    "min" : 25,
    "max" : 50,
  },
  {
    "name" : "Mongrel Raiders",
    "category" : "Core",
    "sticksandstones" : 0,
    "bigrocks" : 0,
    "min" : 10,
    "max" : 20,
  },
  {
    "name" : "Feral Hounds",
    "category" : "Special",
    "conditionalCore" : 8,
    "sticksandstones" : 0,
    "bigrocks" : 0,
    "min" : 5,
    "max" : 15,
  },
  {
    "name" : "Longhorn Herd",
    "category" : "Special",
    "sticksandstones" : 0,
    "bigrocks" : 0,
    "min" : 10,
    "max" : 30,
  },
  {
    "name" : "Minotaurs",
    "category" : "Special",
    "sticksandstones" : 0,
    "bigrocks" : 0,
    "min" : 3,
    "max" : 10,
  },
  {
    "name" : "Centaurs",
    "category" : "Special",
    "sticksandstones" : 0,
    "bigrocks" : 0,
    "min" : 5,
    "max" : 15,
  },
  {
    "name" : "Raiding Chariots",
    "category" : "Special",
    "conditionalCore" : 3,
    "sticksandstones" : 0,
    "bigrocks" : 0,
    "min" : 1,
    "max" : 3,
  },
  {
    "name" : "Razortusk Herd",
    "category" : "Special",
    "sticksandstones" : 0,
    "bigrocks" : 0,
    "min" : 3,
    "max" : 10,
  },
  {
    "name" : "Razortusk Chariot",
    "category" : "Special",
    "sticksandstones" : 0,
    "bigrocks" : 0,
  },
  {
    "name" : "Briar Beast",
    "category" : "Special",
    "sticksandstones" : 0,
    "bigrocks" : 0,
  },
  {
    "name" : "Gargoyles",
    "category" : "Special",
    "sticksandstones" : 0,
    "bigrocks" : 0,
    "min" : 5,
    "max" : 10,
  },
  {
    "name" : "Cyclops",
    "category" : "Terrors of the Wild",
    "sticksandstones" : 0,
    "bigrocks" : 1,
  },
  {
    "name" : "Gortach",
    "category" : "Terrors of the Wild",
    "sticksandstones" : 0,
    "bigrocks" : 0,
  },
  {
    "name" : "Jabberwock",
    "category" : "Terrors of the Wild",
    "sticksandstones" : 0,
    "bigrocks" : 0,
  },
  {
    "name" : "Beast Giant",
    "category" : "Terrors of the Wild",
    "sticksandstones" : 0,
    "bigrocks" : 0,
  },
];

// DE
const DE = [
  {
    "name" : "Techainin and Blaishoi",
    "category" : "Characters",
    "raiders" : 0,
    "boltThrowers" : 0,
  },
  {
    "name" : "The Black Rose",
    "category" : "Characters",
    "raiders" : 0,
    "boltThrowers" : 0,
  },
  {
    "name" : "Dread Prince",
    "category" : "Characters",
    "raiders" : 0,
    "boltThrowers" : 0,
  },
  {
    "name" : "Silexian Officer",
    "category" : "Characters",
    "raiders" : 0,
    "boltThrowers" : 0,
  },
  {
    "name" : "Temple Exarch",
    "category" : "Characters",
    "raiders" : 0,
    "boltThrowers" : 0,
  },
  {
    "name" : "Sanctioned Warlock",
    "category" : "Characters",
    "raiders" : 0,
    "boltThrowers" : 0,
  },
  {
    "name" : "Silent Assassin",
    "category" : "Characters",
    "raiders" : 0,
    "boltThrowers" : 0,
  },
  {
    "name" : "Silexian Spears",
    "category" : "Core",
    "raiders" : 0,
    "boltThrowers" : 0,
    "min" : 15,
    "max" : 35,
  },
  {
    "name" : "Silexian Auxiliaries",
    "category" : "Core",
    "raiders" : 1,
    "boltThrowers" : 0,
    "min" : 10,
    "max" : 25,
  },
  {
    "name" : "Temple Militants",
    "category" : "Core",
    "raiders" : 0,
    "boltThrowers" : 0,
    "min" : 10,
    "max" : 25,
  },
  {
    "name" : "Corsairs",
    "category" : "Core",
    "raiders" : 0,
    "boltThrowers" : 0,
    "min" : 10,
    "max" : 30,
  },
  {
    "name" : "Shadow Riders",
    "category" : "Core",
    "raiders" : 0,
    "boltThrowers" : 0,
    "min" : 5,
    "max" : 10,
  },
  {
    "name" : "Dread Acolytes",
    "category" : "Special",
    "raiders" : 0,
    "boltThrowers" : 0,
    "min" : 5,
    "max" : 12,
  },
  {
    "name" : "Dread Knights",
    "category" : "Special",
    "raiders" : 0,
    "boltThrowers" : 0,
    "min" : 5,
    "max" : 10,
  },
  {
    "name" : "Obsidian Guard",
    "category" : "Special",
    "raiders" : 0,
    "boltThrowers" : 0,
    "min" : 10,
    "max" : 25,
  },
  {
    "name" : "Judicators",
    "category" : "Special",
    "raiders" : 0,
    "boltThrowers" : 0,
    "min" : 10,
    "max" : 25,
  },
  {
    "name" : "Harpies",
    "category" : "Special",
    "raiders" : 0,
    "boltThrowers" : 0,
    "min" : 5,
    "max" : 12,
  },
  {
    "name" : "Gorgons",
    "category" : "Special",
    "raiders" : 0,
    "boltThrowers" : 0,
    "min" : 2,
    "max" : 4,
  },
  {
    "name" : "Thunder Pack",
    "category" : "Special",
    "raiders" : 0,
    "boltThrowers" : 0,
    "min" : 3,
    "max" : 6,
  },
  {
    "name" : "Raptor Chariot",
    "category" : "Special",
    "raiders" : 0,
    "boltThrowers" : 0,
  },
  {
    "name" : "Divine Altar",
    "category" : "Special",
    "raiders" : 0,
    "boltThrowers" : 0,
  },
  {
    "name" : "Hunting Chariot",
    "category" : "Special",
    "raiders" : 0,
    "boltThrowers" : 1,
  },
  {
    "name" : "Repeater Battery",
    "category" : "Special",
    "raiders" : 0,
    "boltThrowers" : 1,
  },
  {
    "name" : "Black Cloaks",
    "category" : "Special",
    "raiders" : 0,
    "boltThrowers" : 0,
    "min" : 5,
    "max" : 10,
  },
  {
    "name" : "Kraken",
    "category" : "The Menagerie",
    "raiders" : 0,
    "boltThrowers" : 0,
  },
  {
    "name" : "Hydra",
    "category" : "The Menagerie",
    "raiders" : 0,
    "boltThrowers" : 0,
  },
  {
    "name" : "Mist Leviathan",
    "category" : "The Menagerie",
    "raiders" : 0,
    "boltThrowers" : 0,
  },
];

// DH
const DH = [
  {
    "name" : "Dinaz Betegoz, Master of the Guild of Lorekeepers",
    "category" : "Characters",
    "clansThunder" : 0,
    "enginesOfWar" : 0,
  },
  {
    "name" : "Tador Berafrig",
    "category" : "Characters",
    "clansThunder" : 0,
    "enginesOfWar" : 0,
  },
  {
    "name" : "King",
    "category" : "Characters",
    "clansThunder" : 0,
    "enginesOfWar" : 0,
  },
  {
    "name" : "Thane",
    "category" : "Characters",
    "clansThunder" : 0,
    "enginesOfWar" : 0,
  },
  {
    "name" : "Runic Smith",
    "category" : "Characters",
    "clansThunder" : 0,
    "enginesOfWar" : 0,
  },
  {
    "name" : "Engineer",
    "category" : "Characters",
    "clansThunder" : 0,
    "enginesOfWar" : 0,
  },
  {
    "name" : "Dragon Seeker",
    "category" : "Characters",
    "clansThunder" : 0,
    "enginesOfWar" : 0,
  },
  {
    "name" : "Clan Warriors",
    "category" : "Core",
    "clansThunder" : 0,
    "enginesOfWar" : 0,
    "min" : 15,
    "max" : 40,
  },
  {
    "name" : "Greybeards",
    "category" : "Core",
    "clansThunder" : 0,
    "enginesOfWar" : 0,
    "min" : 10,
    "max" : 25,
  },
  {
    "name" : "Clan Marksmen",
    "category" : "Core",
    "clansThunder" : 0,
    "enginesOfWar" : 0,
    "min" : 10,
    "max" : 20,
  },
  {
    "name" : "King's Guard",
    "category" : "Special",
    "clansThunder" : 0,
    "enginesOfWar" : 0,
    "min" : 15,
    "max" : 25,
  },
  {
    "name" : "Deep Watch",
    "category" : "Special",
    "clansThunder" : 0,
    "enginesOfWar" : 0,
    "min" : 15,
    "max" : 25,
  },
  {
    "name" : "Seekers",
    "category" : "Special",
    "clansThunder" : 0,
    "enginesOfWar" : 0,
    "min" : 8,
    "max" : 25,
  },
  {
    "name" : "Brothers of Vengeance",
    "category" : "Special",
    "clansThunder" : 0,
    "enginesOfWar" : 0,
    "min" : 8,
    "max" : 15,
  },
  {
    "name" : "Vengeance Seeker",
    "category" : "Special",
    "clansThunder" : 0,
    "enginesOfWar" : 0,
  },
  {
    "name" : "Hold Guardians",
    "category" : "Special",
    "clansThunder" : 0,
    "enginesOfWar" : 0,
    "min" : 3,
    "max" : 6,
  },
  {
    "name" : "Grudge Buster",
    "category" : "Special",
    "clansThunder" : 0,
    "enginesOfWar" : 0,
  },
  {
    "name" : "Miners",
    "category" : "Special",
    "clansThunder" : 0,
    "enginesOfWar" : 0,
    "min" : 10,
    "max" : 20,
  },
  {
    "name" : "Anvil of Power",
    "category" : "Special",
    "clansThunder" : 0,
    "enginesOfWar" : 0,
  },
  {
    "name" : "Rangers",
    "category" : "Special",
    "clansThunder" : 0,
    "enginesOfWar" : 0,
    "min" : 10,
    "max" : 20,
  },
  {
    "name" : "Forge Wardens",
    "category" : "Special",
    "clansThunder" : 0,
    "enginesOfWar" : 0,
    "min" : 10,
    "max" : 16,
  },
  {
    "name" : "Steam Copters",
    "category" : "Special",
    "clansThunder" : 0,
    "enginesOfWar" : 0,
    "min" : 1,
    "max" : 2,
  },
  {
    "name" : "Field Artillery",
    "category" : "Special",
    "clansThunder" : 0,
    "enginesOfWar" : 1,
  },
];

// DL
const DL = [
  {
    "name" : "Tristitia",
    "category" : "Characters",
    "magicShooting" : 0,
  },
  {
    "name" : "Tergon Khan",
    "category" : "Characters",
    "magicShooting" : 0,
  },
  {
    "name" : "Harbinger of Father Chaos",
    "category" : "Characters",
    "magicShooting" : 0,
  },
  {
    "name" : "Kuulima's Deceiver",
    "category" : "Characters",
    "magicShooting" : 0,
  },
  {
    "name" : "Maw of Akaan",
    "category" : "Characters",
    "magicShooting" : 0,
  },
  {
    "name" : "Miser of Sugulag",
    "category" : "Characters",
    "magicShooting" : 0,
  },
  {
    "name" : "Courtesan of Cibaresh",
    "category" : "Characters",
    "magicShooting" : 0,
  },
  {
    "name" : "Omen of Savar",
    "category" : "Characters",
    "magicShooting" : 0,
  },
  {
    "name" : "Sentinel of Nukuja",
    "category" : "Characters",
    "magicShooting" : 0,
  },
  {
    "name" : "Vanadra's Scourge",
    "category" : "Characters",
    "magicShooting" : 0,
  },
  {
    "name" : "Imps",
    "category" : "Core",
    "magicShooting" : 1,
    "min" : 10,
    "max" : 25,
  },
  {
    "name" : "Succubi",
    "category" : "Core",
    "magicShooting" : 0,
    "min" : 10,
    "max" : 25,
  },
  {
    "name" : "Lemures",
    "category" : "Core",
    "magicShooting" : 0,
    "min" : 10,
    "max" : 25,
  },
  {
    "name" : "Myrmidons",
    "category" : "Core",
    "magicShooting" : 0,
    "min" : 10,
    "max" : 25,
  },
  {
    "name" : "Eidolons",
    "category" : "Special",
    "magicShooting" : 3,
    "min" : 5,
    "max" : 10,
  },
  {
    "name" : "Hellhounds",
    "category" : "Special",
    "magicShooting" : 0,
    "min" : 5,
    "max" : 15,
  },
  {
    "name" : "Threshing Engine",
    "category" : "Special",
    "magicShooting" : 0,
    "min" : 1,
    "max" : 3,
  },
  {
    "name" : "Titanslayer Chariot",
    "category" : "Special",
    "magicShooting" : 0,
  },
  {
    "name" : "Mageblight Gremlins",
    "category" : "Special",
    "magicShooting" : 0,
    "min" : 3,
    "max" : 6,
  },
  {
    "name" : "Clawed Fiends",
    "category" : "Special",
    "magicShooting" : 0,
    "min" : 3,
    "max" : 8,
  },
  {
    "name" : "Hoarders",
    "category" : "Special",
    "magicShooting" : 0,
    "min" : 3,
    "max" : 6,
  },
  {
    "name" : "Succubi Tempters",
    "category" : "Special",
    "magicShooting" : 0,
    "min" : 5,
    "max" : 10,
  },
  {
    "name" : "Blazing Glory",
    "category" : "Special",
    "magicShooting" : 0,
  },
  {
    "name" : "Hope Harvester",
    "category" : "Special",
    "magicShooting" : 5,
  },
  {
    "name" : "Brazen Beasts",
    "category" : "Special",
    "magicShooting" : 0,
    "min" : 3,
    "max" : 5,
  },
  {
    "name" : "Furies",
    "category" : "Aves",
    "magicShooting" : 0,
    "min" : 5,
    "max" : 15,
  },
  {
    "name" : "Veil Serpents",
    "category" : "Aves",
    "magicShooting" : 0,
    "min" : 3,
    "max" : 6,
  },
  {
    "name" : "Bloat Flies",
    "category" : "Aves",
    "magicShooting" : 0,
    "min" : 3,
    "max" : 5,
  },
];

// EoS
const EoS = [
  {
    "name" : "Heinrich Falkenbach",
    "category" : "Characters",
    "imperialAuxiliaries" : 0,
    "imperialArmory" : 0,
  },
  {
    "name" : "Brother Tomaz",
    "category" : "Characters",
    "imperialAuxiliaries" : 0,
    "imperialArmory" : 0,
  },
  {
    "name" : "Marshal",
    "category" : "Characters",
    "imperialAuxiliaries" : 0,
    "imperialArmory" : 0,
  },
  {
    "name" : "Knight Commander",
    "category" : "Characters",
    "imperialAuxiliaries" : 0,
    "imperialArmory" : 0,
  },
  {
    "name" : "Battlefield Wizard",
    "category" : "Characters",
    "imperialAuxiliaries" : 0,
    "imperialArmory" : 0,
  },
  {
    "name" : "Prelate",
    "category" : "Characters",
    "imperialAuxiliaries" : 0,
    "imperialArmory" : 0,
  },
  {
    "name" : "Artificer",
    "category" : "Characters",
    "imperialAuxiliaries" : 0,
    "imperialArmory" : 0,
  },
  {
    "name" : "Inquisitor",
    "category" : "Characters",
    "imperialAuxiliaries" : 0,
    "imperialArmory" : 0,
  },
  {
    "name" : "State Infantry",
    "category" : "Core",
    "imperialAuxiliaries" : 0,
    "imperialArmory" : 0,
    "min" : 20,
    "max" : 40,
  },
  {
    "name" : "State Detachment",
    "category" : "Core",
    "imperialAuxiliaries" : 0,
    "imperialArmory" : 0,
    "min" : 15,
    "max" : 20,
  },
  {
    "name" : "State Marksmen",
    "category" : "Core",
    "imperialAuxiliaries" : 1,
    "imperialArmory" : 0,
    "min" : 15,
    "max" : 20,
  },
  {
    "name" : "Local Militia",
    "category" : "Core",
    "imperialAuxiliaries" : 1,
    "imperialArmory" : 0,
    "min" : 15,
    "max" : 25,
  },
  {
    "name" : "Electoral Cavalry",
    "category" : "Core",
    "imperialAuxiliaries" : 0,
    "imperialArmory" : 0,
    "min" : 8,
    "max" : 20,
  },
  {
    "name" : "Knightly Orders",
    "category" : "Core",
    "imperialAuxiliaries" : 0,
    "imperialArmory" : 0,
    "min" : 5,
    "max" : 15,
  },
  {
    "name" : "Imperial Guard",
    "category" : "Special",
    "imperialAuxiliaries" : 0,
    "imperialArmory" : 0,
    "min" : 15,
    "max" : 30,
  },
  {
    "name" : "Imperial Detachment",
    "category" : "Special",
    "imperialAuxiliaries" : 0,
    "imperialArmory" : 0,
    "min" : 15,
    "max" : 15,
  },
  {
    "name" : "Knights of the Sun Griffon",
    "category" : "Special",
    "imperialAuxiliaries" : 0,
    "imperialArmory" : 0,
    "min" : 3,
    "max" : 5,
  },
  {
    "name" : "Arcane Engine",
    "category" : "Special",
    "imperialAuxiliaries" : 0,
    "imperialArmory" : 0,
  },
  {
    "name" : "Imperial Rangers",
    "category" : "Special",
    "imperialAuxiliaries" : 1,
    "imperialArmory" : 0,
    "min" : 8,
    "max" : 15,
  },
  {
    "name" : "Reiters",
    "category" : "Special",
    "imperialAuxiliaries" : 1,
    "imperialArmory" : 0,
    "min" : 5,
    "max" : 10,
  },
  {
    "name" : "Blackpowder Artillery",
    "category" : "Special",
    "imperialAuxiliaries" : 0,
    "imperialArmory" : 1,
  },
  {
    "name" : "Flagellants",
    "category" : "Sunna's Fury",
    "imperialAuxiliaries" : 0,
    "imperialArmory" : 0,
    "min" : 15,
    "max" : 30,
  },
  {
    "name" : "Steam Tank",
    "category" : "Sunna's Fury",
    "imperialAuxiliaries" : 0,
    "imperialArmory" : 1,
  },
];

// HE
const HE = [
  {
    "name" : "Acadnath, the Scholar",
    "category" : "Characters",
    "queensBows" : 0,
    "navalOrdnance" : 0,
    "ancientAllies" : 0,
  },
  {
    "name" : "Tenacla and Baluruth",
    "category" : "Characters",
    "queensBows" : 0,
    "navalOrdnance" : 0,
    "ancientAllies" : 0,
  },
  {
    "name" : "High Prince",
    "category" : "Characters",
    "queensBows" : 0,
    "navalOrdnance" : 0,
    "ancientAllies" : 0,
  },
  {
    "name" : "Commander",
    "category" : "Characters",
    "queensBows" : 0,
    "navalOrdnance" : 0,
    "ancientAllies" : 0,
  },
  {
    "name" : "Mage",
    "category" : "Characters",
    "queensBows" : 0,
    "navalOrdnance" : 0,
    "ancientAllies" : 0,
  },
  {
    "name" : "Citizen Archers",
    "category" : "Core",
    "queensBows" : 1,
    "navalOrdnance" : 0,
    "ancientAllies" : 0,
    "min" : 15,
    "max" : 30,
  },
  {
    "name" : "Citizen Spears",
    "category" : "Core",
    "queensBows" : 0,
    "navalOrdnance" : 0,
    "ancientAllies" : 0,
    "min" : 20,
    "max" : 40,
  },
  {
    "name" : "Sea Guard",
    "category" : "Core",
    "queensBows" : 1,
    "navalOrdnance" : 0,
    "ancientAllies" : 0,
    "min" : 15,
    "max" : 30,
  },
  {
    "name" : "Highborn Lancers",
    "category" : "Core",
    "queensBows" : 0,
    "navalOrdnance" : 0,
    "ancientAllies" : 0,
    "min" : 5,
    "max" : 15,
  },
  {
    "name" : "Erlein Reavers",
    "category" : "Core",
    "queensBows" : 0,
    "navalOrdnance" : 0,
    "ancientAllies" : 0,
    "min" : 5,
    "max" : 10,
  },
  {
    "name" : "Sword Masters",
    "category" : "Special",
    "queensBows" : 0,
    "navalOrdnance" : 0,
    "ancientAllies" : 0,
    "min" : 10,
    "max" : 25,
  },
  {
    "name" : "Lion Guard",
    "category" : "Special",
    "queensBows" : 0,
    "navalOrdnance" : 0,
    "ancientAllies" : 0,
    "min" : 10,
    "max" : 25,
  },
  {
    "name" : "Flame Wardens",
    "category" : "Special",
    "queensBows" : 0,
    "navalOrdnance" : 0,
    "ancientAllies" : 0,
    "min" : 10,
    "max" : 25,
  },
  {
    "name" : "Knights of Rymâ",
    "category" : "Special",
    "queensBows" : 0,
    "navalOrdnance" : 0,
    "ancientAllies" : 0,
    "min" : 5,
    "max" : 10,
  },
  {
    "name" : "Reaver Chariots",
    "category" : "Special",
    "queensBows" : 0,
    "navalOrdnance" : 0,
    "ancientAllies" : 0,
    "min" : 2,
    "max" : 3,
  },
  {
    "name" : "Lion Chariot",
    "category" : "Special",
    "queensBows" : 0,
    "navalOrdnance" : 0,
    "ancientAllies" : 0,
  },
  {
    "name" : "Giant Eagles",
    "category" : "Special",
    "queensBows" : 0,
    "navalOrdnance" : 0,
    "ancientAllies" : 0,
    "min" : 1,
    "max" : 5,
  },
  {
    "name" : "Initiate of the Fiery Heart",
    "category" : "Special",
    "queensBows" : 0,
    "navalOrdnance" : 0,
    "ancientAllies" : 1,
  },
  {
    "name" : "Phoenix",
    "category" : "Special",
    "queensBows" : 0,
    "navalOrdnance" : 0,
    "ancientAllies" : 1,
  },
  {
    "name" : "Sea Guard Reaper",
    "category" : "Special",
    "queensBows" : 0,
    "navalOrdnance" : 1,
    "ancientAllies" : 0,
  },
  {
    "name" : "Sky Sloop",
    "category" : "Special",
    "queensBows" : 0,
    "navalOrdnance" : 1,
    "ancientAllies" : 0,
  },
  {
    "name" : "Queen's Guard",
    "category" : "Special",
    "queensBows" : 1,
    "navalOrdnance" : 0,
    "ancientAllies" : 0,
    "min" : 10,
    "max" : 20,
  },
  {
    "name" : "Grey Watchers",
    "category" : "Special",
    "queensBows" : 1,
    "navalOrdnance" : 0,
    "ancientAllies" : 0,
    "min" : 5,
    "max" : 10,
  },
];

// ID
const ID = [
  {
    "name" : "Abazzalem, the Mechanical Lamassu",
    "category" : "Characters",
    "firesOfIndustry" : 0,
    "blackPowder" : 0,
  },
  {
    "name" : "Ibat-Sokavum, the Flying Charioteer",
    "category" : "Characters",
    "firesOfIndustry" : 0,
    "blackPowder" : 0,
  },
  {
    "name" : "Overlord",
    "category" : "Characters",
    "firesOfIndustry" : 0,
    "blackPowder" : 0,
  },
  {
    "name" : "Prophet",
    "category" : "Characters",
    "firesOfIndustry" : 0,
    "blackPowder" : 0,
  },
  {
    "name" : "Vizier",
    "category" : "Characters",
    "firesOfIndustry" : 0,
    "blackPowder" : 0,
  },
  {
    "name" : "Taurukh Commissioner",
    "category" : "Characters",
    "firesOfIndustry" : 0,
    "blackPowder" : 0,
  },
  {
    "name" : "Vassal Conjurer",
    "category" : "Characters",
    "firesOfIndustry" : 0,
    "blackPowder" : 0,
  },
  {
    "name" : "Lamassu Scholar",
    "category" : "Characters",
    "firesOfIndustry" : 0,
    "blackPowder" : 0,
  },
  {
    "name" : "Infernal Warriors",
    "category" : "Core",
    "firesOfIndustry" : 0,
    "blackPowder" : 0,
    "min" : 20,
    "max" : 40,
  },
  {
    "name" : "Citadel Guard",
    "category" : "Core",
    "firesOfIndustry" : 0,
    "blackPowder" : 0,
    "min" : 15,
    "max" : 25,
  },
  {
    "name" : "Vassal Levies",
    "category" : "Core",
    "firesOfIndustry" : 0,
    "blackPowder" : 0,
    "min" : 20,
    "max" : 40,
  },
  {
    "name" : "Shackled Slaves",
    "category" : "Core",
    "firesOfIndustry" : 0,
    "blackPowder" : 0,
    "min" : 20,
    "max" : 40,
  },
  {
    "name" : "Kadim Incarnates",
    "category" : "Special",
    "firesOfIndustry" : 0,
    "blackPowder" : 0,
    "min" : 3,
    "max" : 6,
  },
  {
    "name" : "Kadim Chariot",
    "category" : "Special",
    "firesOfIndustry" : 0,
    "blackPowder" : 0,
  },
  {
    "name" : "Immortals",
    "category" : "Special",
    "firesOfIndustry" : 0,
    "blackPowder" : 0,
    "min" : 15,
    "max" : 25,
  },
  {
    "name" : "Disciples of Lugar",
    "category" : "Special",
    "firesOfIndustry" : 0,
    "blackPowder" : 0,
    "min" : 15,
    "max" : 25,
  },
  {
    "name" : "Taurukh Enforcers",
    "category" : "Special",
    "firesOfIndustry" : 0,
    "blackPowder" : 0,
    "min" : 5,
    "max" : 12,
  },
  {
    "name" : "Taurukh Anointed",
    "category" : "Special",
    "firesOfIndustry" : 0,
    "blackPowder" : 0,
    "min" : 3,
    "max" : 5,
  },
  {
    "name" : "Vassal Cavalry",
    "category" : "Special",
    "firesOfIndustry" : 0,
    "blackPowder" : 0,
    "min" : 5,
    "max" : 15,
  },
  {
    "name" : "Vassal Slingshot",
    "category" : "Special",
    "firesOfIndustry" : 0,
    "blackPowder" : 0,
  },
  {
    "name" : "Gunnery Team",
    "category" : "Special",
    "firesOfIndustry" : 0,
    "blackPowder" : 0,
  },
  {
    "name" : "Infernal Artillery",
    "category" : "Special",
    "firesOfIndustry" : 0,
    "blackPowder" : 0,
  },
  {
    "name" : "Infernal Bastion",
    "category" : "Special",
    "firesOfIndustry" : 0,
    "blackPowder" : 0,
  },
  {
    "name" : "Infernal Engine",
    "category" : "Instruments of Destruction",
    "firesOfIndustry" : 0,
    "blackPowder" : 0,
  },
  {
    "name" : "Kadim Titan",
    "category" : "Instruments of Destruction",
    "firesOfIndustry" : 0,
    "blackPowder" : 0,
  },
  {
    "name" : "Citizen Giant",
    "category" : "Instruments of Destruction",
    "firesOfIndustry" : 0,
    "blackPowder" : 0,
  },
];

// KoE
const KoE = [
  {
    "name" : "King Henry the Young",
    "category" : "Characters",
    "gallantry" : 0,
    "smallArmsFire" : 0,
    "siegeEngines" : 0,
  },
  {
    "name" : "Hernaut Le Rouquin",
    "category" : "Characters",
    "gallantry" : 0,
    "smallArmsFire" : 0,
    "siegeEngines" : 0,
  },
  {
    "name" : "Damsel",
    "category" : "Characters",
    "gallantry" : 0,
    "smallArmsFire" : 0,
    "siegeEngines" : 0,
  },
  {
    "name" : "Duke",
    "category" : "Characters",
    "gallantry" : 0,
    "smallArmsFire" : 0,
    "siegeEngines" : 0,
  },
  {
    "name" : "Paladin",
    "category" : "Characters",
    "gallantry" : 0,
    "smallArmsFire" : 0,
    "siegeEngines" : 0,
  },
  {
    "name" : "Folk Hero",
    "category" : "Characters",
    "gallantry" : 0,
    "smallArmsFire" : 0,
    "siegeEngines" : 0,
  },
  {
    "name" : "Knights of the Realm",
    "category" : "Core",
    "gallantry" : 0,
    "smallArmsFire" : 0,
    "siegeEngines" : 0,
    "min" : 6,
    "max" : 12,
  },
  {
    "name" : "Hedge Knights",
    "category" : "Core",
    "gallantry" : 2,
    "smallArmsFire" : 0,
    "siegeEngines" : 0,
    "min" : 6,
    "max" : 9,
  },
  {
    "name" : "Mounted Serjeants",
    "category" : "Core",
    "gallantry" : 0,
    "smallArmsFire" : 0,
    "siegeEngines" : 0,
    "min" : 8,
    "max" : 15,
  },
  {
    "name" : "Lowborn Levies",
    "category" : "Core",
    "gallantry" : 0,
    "smallArmsFire" : 0,
    "siegeEngines" : 0,
    "min" : 30,
    "max" : 50,
  },
  {
    "name" : "Lowborn Archers",
    "category" : "Core",
    "gallantry" : 0,
    "smallArmsFire" : 0,
    "siegeEngines" : 0,
    "min" : 15,
    "max" : 30,
  },
  {
    "name" : "Men-at-Arms",
    "category" : "Special",
    "gallantry" : 0,
    "smallArmsFire" : 0,
    "siegeEngines" : 0,
    "min" : 15,
    "max" : 30,
  },
  {
    "name" : "Sacred Reliquary",
    "category" : "Special",
    "gallantry" : 0,
    "smallArmsFire" : 0,
    "siegeEngines" : 0,
  },
  {
    "name" : "Knights of the Court",
    "category" : "Special",
    "gallantry" : 0,
    "smallArmsFire" : 0,
    "siegeEngines" : 0,
    "min" : 6,
    "max" : 12,
  },
  {
    "name" : "Knights Penitent",
    "category" : "Special",
    "gallantry" : 0,
    "smallArmsFire" : 0,
    "siegeEngines" : 0,
    "min" : 3,
    "max" : 9,
  },
  {
    "name" : "Knights of the Quest",
    "category" : "Special",
    "gallantry" : 0,
    "smallArmsFire" : 0,
    "siegeEngines" : 0,
    "min" : 6,
    "max" : 9,
  },
  {
    "name" : "Yeoman Outriders",
    "category" : "Special",
    "gallantry" : 0,
    "smallArmsFire" : 0,
    "siegeEngines" : 0,
    "min" : 5,
    "max" : 15,
  },
  {
    "name" : "Enlisted Outlaws",
    "category" : "Special",
    "gallantry" : 0,
    "smallArmsFire" : 0,
    "siegeEngines" : 0,
    "min" : 10,
    "max" : 15,
  },
  {
    "name" : "Siege Weapon",
    "category" : "Special",
    "gallantry" : 0,
    "smallArmsFire" : 0,
    "siegeEngines" : 1,
  },
  {
    "name" : "Pegasus Knights",
    "category" : "Special",
    "gallantry" : 2,
    "smallArmsFire" : 0,
    "siegeEngines" : 0,
    "min" : 3,
    "max" : 5,
  },
  {
    "name" : "Sky Heralds",
    "category" : "Special",
    "gallantry" : 1,
    "smallArmsFire" : 0,
    "siegeEngines" : 0,
    "min" : 3,
    "max" : 6,
  },
  {
    "name" : "Naiads",
    "category" : "Fey",
    "gallantry" : 0,
    "smallArmsFire" : 0,
    "siegeEngines" : 0,
    "min" : 5,
    "max" : 10,
  },
  {
    "name" : "Friar's Lantern",
    "category" : "Fey",
    "gallantry" : 0,
    "smallArmsFire" : 0,
    "siegeEngines" : 0,
  },
  {
    "name" : "The Lady's Courtier",
    "category" : "Fey",
    "gallantry" : 0,
    "smallArmsFire" : 0,
    "siegeEngines" : 0,
  },
  {
    "name" : "Fey Knight",
    "category" : "Fey",
    "gallantry" : 1,
    "smallArmsFire" : 0,
    "siegeEngines" : 0,
  },
];

// OK
const OK = [
  {
    "name" : "Ganzorig, the Ironbond",
    "category" : "Characters",
    "hiredGuns" : 0,
    "powderKeg" : 0,
  },
  {
    "name" : "Valish, the Chefling",
    "category" : "Characters",
    "hiredGuns" : 0,
    "powderKeg" : 0,
  },
  {
    "name" : "Great Khan",
    "category" : "Characters",
    "hiredGuns" : 0,
    "powderKeg" : 0,
  },
  {
    "name" : "Khan",
    "category" : "Characters",
    "hiredGuns" : 0,
    "powderKeg" : 0,
  },
  {
    "name" : "Shaman",
    "category" : "Characters",
    "hiredGuns" : 0,
    "powderKeg" : 0,
  },
  {
    "name" : "Mammoth Hunter",
    "category" : "Characters",
    "hiredGuns" : 0,
    "powderKeg" : 0,
  },
  {
    "name" : "Tribesmen",
    "category" : "Core",
    "hiredGuns" : 0,
    "powderKeg" : 0,
    "min" : 4,
    "max" : 15,
  },
  {
    "name" : "Bruisers",
    "category" : "Core",
    "hiredGuns" : 0,
    "powderKeg" : 0,
    "min" : 3,
    "max" : 10,
  },
  {
    "name" : "Scraplings",
    "category" : "Core",
    "hiredGuns" : 0,
    "powderKeg" : 0,
    "min" : 20,
    "max" : 60,
  },
  {
    "name" : "Sabretooth Tigers",
    "category" : "Special",
    "conditionalCore" : 5,
    "hiredGuns" : 0,
    "powderKeg" : 0,
    "min" : 3,
    "max" : 15,
  },
  {
    "name" : "Scrapling Trappers",
    "category" : "Special",
    "hiredGuns" : 0,
    "powderKeg" : 0,
    "min" : 8,
    "max" : 15,
  },
  {
    "name" : "Yetis",
    "category" : "Special",
    "hiredGuns" : 0,
    "powderKeg" : 0,
    "min" : 2,
    "max" : 5,
  },
  {
    "name" : "Kin-Eater",
    "category" : "Special",
    "hiredGuns" : 0,
    "powderKeg" : 0,
  },
  {
    "name" : "Tusker Cavalry",
    "category" : "Special",
    "hiredGuns" : 0,
    "powderKeg" : 0,
    "min" : 3,
    "max" : 5,
  },
  {
    "name" : "Mercenary Veterans",
    "category" : "Special",
    "hiredGuns" : 0,
    "powderKeg" : 0,
    "min" : 3,
    "max" : 9,
  },
  {
    "name" : "Mercenary Gunners",
    "category" : "Special",
    "hiredGuns" : 0,
    "powderKeg" : 0,
    "min" : 3,
    "max" : 6,
  },
  {
    "name" : "Bombardiers",
    "category" : "Special",
    "hiredGuns" : 0,
    "powderKeg" : 0,
    "min" : 3,
    "max" : 8,
  },
  {
    "name" : "Thunder Cannon",
    "category" : "Special",
    "hiredGuns" : 0,
    "powderKeg" : 1,
  },
  {
    "name" : "Scratapult",
    "category" : "Special",
    "hiredGuns" : 0,
    "powderKeg" : 1,
  },
  {
    "name" : "Rock Aurochs",
    "category" : "Chained Beasts",
    "hiredGuns" : 0,
    "powderKeg" : 0,
  },
  {
    "name" : "Frost Mammoth",
    "category" : "Chained Beasts",
    "hiredGuns" : 0,
    "powderKeg" : 0,
  },
  {
    "name" : "Mercenary Giant",
    "category" : "Chained Beasts",
    "hiredGuns" : 0,
    "powderKeg" : 0,
  },
];

// OnG
const OnG = [
  {
    "name" : "Lerrgog, the Smart Troll",
    "category" : "Characters",
    "bigAndNasty" : 0,
    "deathFromAbove" : 0,
    "archerBroods" : 0,
  },
  {
    "name" : "Amokek, the Only King?",
    "category" : "Characters",
    "bigAndNasty" : 0,
    "deathFromAbove" : 0,
    "archerBroods" : 0,
  },
  {
    "name" : "The Splendid Leader",
    "category" : "Characters",
    "bigAndNasty" : 0,
    "deathFromAbove" : 0,
    "archerBroods" : 0,
  },
  {
    "name" : "Orc Warlord",
    "category" : "Characters",
    "bigAndNasty" : 0,
    "deathFromAbove" : 0,
    "archerBroods" : 0,
  },
  {
    "name" : "Iron Orc Loner",
    "category" : "Characters",
    "bigAndNasty" : 0,
    "deathFromAbove" : 0,
    "archerBroods" : 0,
  },
  {
    "name" : "Brood Alpha",
    "category" : "Characters",
    "bigAndNasty" : 0,
    "deathFromAbove" : 0,
    "archerBroods" : 0,
  },
  {
    "name" : "Orc Shaman",
    "category" : "Characters",
    "bigAndNasty" : 0,
    "deathFromAbove" : 0,
    "archerBroods" : 0,
  },
  {
    "name" : "Goblin Demagogue",
    "category" : "Characters",
    "bigAndNasty" : 0,
    "deathFromAbove" : 0,
    "archerBroods" : 0,
  },
  {
    "name" : "Goblin Witch",
    "category" : "Characters",
    "bigAndNasty" : 0,
    "deathFromAbove" : 0,
    "archerBroods" : 0,
  },
  {
    "name" : "Gogtuk Initiate",
    "category" : "Characters",
    "bigAndNasty" : 0,
    "deathFromAbove" : 0,
    "archerBroods" : 0,
  },
  {
    "name" : "Mad Git",
    "category" : "Characters",
    "bigAndNasty" : 0,
    "deathFromAbove" : 0,
    "archerBroods" : 0,
  },
  {
    "name" : "Goblin Rabble",
    "category" : "Core",
    "bigAndNasty" : 0,
    "deathFromAbove" : 0,
    "archerBroods" : 0,
    "min" : 25,
    "max" : 60,
  },
  {
    "name" : "Goblin Reavers",
    "category" : "Core",
    "bigAndNasty" : 0,
    "deathFromAbove" : 0,
    "archerBroods" : 0,
    "min" : 8,
    "max" : 25,
  },
  {
    "name" : "Feral Orcs",
    "category" : "Core",
    "bigAndNasty" : 0,
    "deathFromAbove" : 0,
    "archerBroods" : 0,
    "min" : 25,
    "max" : 50,
  },
  {
    "name" : "Feral Orc Marauders",
    "category" : "Core",
    "bigAndNasty" : 0,
    "deathFromAbove" : 0,
    "archerBroods" : 0,
    "min" : 10,
    "max" : 25,
  },
  {
    "name" : "Veteran Orcs",
    "category" : "Core",
    "bigAndNasty" : 0,
    "deathFromAbove" : 0,
    "archerBroods" : 0,
    "min" : 20,
    "max" : 40,
  },
  {
    "name" : "Veteran Orc Marauders",
    "category" : "Core",
    "bigAndNasty" : 0,
    "deathFromAbove" : 0,
    "archerBroods" : 0,
    "min" : 5,
    "max" : 15,
  },
  {
    "name" : "Iron Orcs",
    "category" : "Special",
    "bigAndNasty" : 0,
    "deathFromAbove" : 0,
    "archerBroods" : 0,
    "min" : 15,
    "max" : 30,
  },
  {
    "name" : "Iron Orc Chariots",
    "category" : "Special",
    "bigAndNasty" : 0,
    "deathFromAbove" : 0,
    "archerBroods" : 0,
    "min" : 1,
    "max" : 2,
  },
  {
    "name" : "Gogtuk Neophytes",
    "category" : "Special",
    "bigAndNasty" : 0,
    "deathFromAbove" : 0,
    "archerBroods" : 0,
    "min" : 10,
    "max" : 20,
  },
  {
    "name" : "Goblin Chariots",
    "category" : "Special",
    "bigAndNasty" : 0,
    "deathFromAbove" : 0,
    "archerBroods" : 0,
    "min" : 2,
    "max" : 3,
  },
  {
    "name" : "Grotlings",
    "category" : "Special",
    "bigAndNasty" : 0,
    "deathFromAbove" : 0,
    "archerBroods" : 0,
    "min" : 3,
    "max" : 6,
  },
  {
    "name" : "Grotling Scrap Wagon",
    "category" : "Special",
    "bigAndNasty" : 0,
    "deathFromAbove" : 0,
    "archerBroods" : 0,
  },
  {
    "name" : "Gnashers",
    "category" : "Special",
    "bigAndNasty" : 0,
    "deathFromAbove" : 0,
    "archerBroods" : 0,
    "min" : 15,
    "max" : 40,
  },
  {
    "name" : "Gnashers Dashers",
    "category" : "Special",
    "bigAndNasty" : 0,
    "deathFromAbove" : 0,
    "archerBroods" : 0,
    "min" : 10,
    "max" : 15,
  },
  {
    "name" : "Gnasher Dashers",
    "category" : "Special",
    "bigAndNasty" : 0,
    "deathFromAbove" : 0,
    "archerBroods" : 0,
    "min" : 10,
    "max" : 15,
  },
  {
    "name" : "Wrecking Team",
    "category" : "Special",
    "bigAndNasty" : 0,
    "deathFromAbove" : 0,
    "archerBroods" : 0,
  },
  {
    "name" : "Trolls",
    "category" : "Special",
    "bigAndNasty" : 0,
    "deathFromAbove" : 0,
    "archerBroods" : 0,
    "min" : 3,
    "max" : 9,
  },
  {
    "name" : "Goblin Artillery",
    "category" : "Special",
    "bigAndNasty" : 0,
    "deathFromAbove" : 1,
    "archerBroods" : 0,
  },
  {
    "name" : "Giant",
    "category" : "Special",
    "bigAndNasty" : 1,
    "deathFromAbove" : 0,
    "archerBroods" : 0,
  },
  {
    "name" : "Guardian Behemoth",
    "category" : "Special",
    "bigAndNasty" : 1,
    "deathFromAbove" : 0,
    "archerBroods" : 0,
  },
  {
    "name" : "Great Green Idol",
    "category" : "Special",
    "bigAndNasty" : 1,
    "deathFromAbove" : 0,
    "archerBroods" : 0,
  },
];

// SA
const SA = [
  {
    "name" : "Anurarch Destined",
    "category" : "Characters",
    "saurianShooting" : 0,
  },
  {
    "name" : "Shade and Stone",
    "category" : "Characters",
    "saurianShooting" : 0,
  },
  {
    "name" : "Anurarch Archmage",
    "category" : "Characters",
    "saurianShooting" : 0,
  },
  {
    "name" : "Caiman Mentor",
    "category" : "Characters",
    "saurianShooting" : 0,
  },
  {
    "name" : "Tegu Veteran",
    "category" : "Characters",
    "saurianShooting" : 0,
  },
  {
    "name" : "Skink Veteran",
    "category" : "Characters",
    "saurianShooting" : 0,
  },
  {
    "name" : "Tegu Warriors",
    "category" : "Core",
    "saurianShooting" : 0,
    "min" : 15,
    "max" : 30,
  },
  {
    "name" : "Skink Warriors",
    "category" : "Core",
    "saurianShooting" : 0,
    "min" : 20,
    "max" : 40,
  },
  {
    "name" : "Skink Hunters",
    "category" : "Core",
    "saurianShooting" : 1,
    "min" : 12,
    "max" : 20,
  },
  {
    "name" : "Caiman Warriors",
    "category" : "Core",
    "saurianShooting" : 0,
    "min" : 4,
    "max" : 8,
  },
  {
    "name" : "Tegu Guards",
    "category" : "Special",
    "saurianShooting" : 0,
    "min" : 15,
    "max" : 25,
  },
  {
    "name" : "Tegu Mystics",
    "category" : "Special",
    "saurianShooting" : 0,
    "min" : 10,
    "max" : 20,
  },
  {
    "name" : "Raptor Pack",
    "category" : "Special",
    "saurianShooting" : 0,
    "min" : 6,
    "max" : 15,
  },
  {
    "name" : "Raptor Riders",
    "category" : "Special",
    "saurianShooting" : 0,
    "min" : 8,
    "max" : 15,
  },
  {
    "name" : "Caiman Elders",
    "category" : "Special",
    "saurianShooting" : 0,
    "min" : 3,
    "max" : 6,
  },
  {
    "name" : "Thyroscutus Herd",
    "category" : "Special",
    "saurianShooting" : 0,
    "min" : 1,
    "max" : 3,
  },
  {
    "name" : "Rhamphodon Riders",
    "category" : "Special",
    "saurianShooting" : 0,
    "min" : 3,
    "max" : 6,
  },
  {
    "name" : "Saurian Swarms",
    "category" : "Special",
    "saurianShooting" : 0,
    "min" : 3,
    "max" : 6,
  },
  {
    "name" : "Skink Guerrillas",
    "category" : "Special",
    "saurianShooting" : 0,
    "min" : 8,
    "max" : 15,
  },
  {
    "name" : "Weapon Beasts",
    "category" : "Special",
    "saurianShooting" : 2,
    "min" : 2,
    "max" : 4,
  },
  {
    "name" : "Pteradon Riders",
    "category" : "Special",
    "saurianShooting" : 0,
    "min" : 3,
    "max" : 6,
  },
  {
    "name" : "Stygiosaur Pack",
    "category" : "Magna Sauria",
    "saurianShooting" : 0,
    "min" : 2,
    "max" : 4,
  },
  {
    "name" : "Carnosaur",
    "category" : "Magna Sauria",
    "saurianShooting" : 0,
  },
  {
    "name" : "Taurosaur",
    "category" : "Magna Sauria",
    "saurianShooting" : 0,
  },
  {
    "name" : "Titanopod",
    "category" : "Magna Sauria",
    "saurianShooting" : 0,
  },
];

// SE
const SE = [
  {
    "name" : "Dwatobel, The World-Wandering Tree",
    "category" : "Characters",
    "sylvanShooting" : 0,
    "sylvanBeasts" : 0
  },
  {
    "name" : "Domethloc, The Unicorn Shapeshifter",
    "category" : "Characters",
    "sylvanShooting" : 0,
    "sylvanBeasts" : 0
  },
  {
    "name" : "Forest Prince",
    "category" : "Characters",
    "sylvanShooting" : 0,
    "sylvanBeasts" : 0
  },
  {
    "name" : "Chieftain",
    "category" : "Characters",
    "sylvanShooting" : 0,
    "sylvanBeasts" : 0
  },
  {
    "name" : "Druid",
    "category" : "Characters",
    "sylvanShooting" : 0,
    "sylvanBeasts" : 0
  },
  {
    "name" : "Dryad Ancient",
    "category" : "Characters",
    "sylvanShooting" : 0,
    "sylvanBeasts" : 0
  },
  {
    "name" : "Avatar of Nature",
    "category" : "Characters",
    "sylvanShooting" : 0,
    "sylvanBeasts" : 2,
  },
  {
    "name" : "Treefather Ancient",
    "category" : "Characters",
    "sylvanShooting" : 0,
    "sylvanBeasts" : 1,
  },
  {
    "name" : "Thicket Shepherd",
    "category" : "Characters",
    "sylvanShooting" : 0,
    "sylvanBeasts" : 0,
  },
  {
    "name" : "Forest Guard",
    "category" : "Core",
    "sylvanShooting" : 0,
    "sylvanBeasts" : 0,
    "min" : 15,
    "max" : 35,
  },
  {
    "name" : "Sylvan Archers",
    "category" : "Core",
    "sylvanShooting" : 1,
    "sylvanBeasts" : 0,
    "min" : 10,
    "max" : 25,
  },
  {
    "name" : "Heath Riders",
    "category" : "Core",
    "sylvanShooting" : 0,
    "sylvanBeasts" : 0,
    "min" : 5,
    "max" : 15,
  },
  {
    "name" : "Dryads",
    "category" : "Core",
    "sylvanShooting" : 0,
    "sylvanBeasts" : 0,
    "min" : 10,
    "max" : 25,
  },
  {
    "name" : "Forest Rangers",
    "category" : "Special",
    "sylvanShooting" : 0,
    "sylvanBeasts" : 0,
    "min" : 10,
    "max" : 25,
  },
  {
    "name" : "Thicket Beasts",
    "category" : "Special",
    "sylvanShooting" : 0,
    "sylvanBeasts" : 0,
    "min" : 4,
    "max" : 6,
  },
  {
    "name" : "Forest Eagles",
    "category" : "Special",
    "sylvanShooting" : 0,
    "sylvanBeasts" : 0,
    "min" : 1,
    "max" : 5,
  },
  {
    "name" : "Blade Dancers",
    "category" : "Special",
    "sylvanShooting" : 0,
    "sylvanBeasts" : 0,
    "min" : 7,
    "max" : 15,
  },
  {
    "name" : "Treefather",
    "category" : "Special",
    "sylvanShooting" : 0,
    "sylvanBeasts" : 1,
  },
  {
    "name" : "Wild Huntsmen",
    "category" : "Special",
    "sylvanShooting" : 0,
    "sylvanBeasts" : 0,
    "min" : 5,
    "max" : 10,
  },
  {
    "name" : "Kestrel Knights",
    "category" : "Special",
    "sylvanShooting" : 0,
    "sylvanBeasts" : 0,
    "min" : 3,
    "max" : 4,
  },
  {
    "name" : "Briar Maidens",
    "category" : "Unseen Arrows",
    "sylvanShooting" : 0.5,
    "sylvanBeasts" : 0,
    "min" : 5,
    "max" : 10,
  },
  {
    "name" : "Sylvan Sentinels",
    "category" : "Unseen Arrows",
    "sylvanShooting" : 2,
    "sylvanBeasts" : 0,
    "min" : 5,
    "max" : 10,
  },
  {
    "name" : "Pathfinders",
    "category" : "Unseen Arrows",
    "sylvanShooting" : 2,
    "sylvanBeasts" : 0,
    "min" : 5,
    "max" : 10,
  },
];

// UD
const UD = [
  {
    "name" : "Rehnepeh, the Undying Sun",
    "category" : "Characters",
    "aspisArrows" : 0,
    "deathFromAfar" : 0,
  },
  {
    "name" : "Ashotet, Custodian of Souls",
    "category" : "Characters",
    "aspisArrows" : 0,
    "deathFromAfar" : 0,
  },
  {
    "name" : "Pharaoh",
    "category" : "Characters",
    "aspisArrows" : 0,
    "deathFromAfar" : 0,
  },
  {
    "name" : "Nomarch",
    "category" : "Characters",
    "aspisArrows" : 0,
    "deathFromAfar" : 0,
  },
  {
    "name" : "Death Cult Hierarch",
    "category" : "Characters",
    "aspisArrows" : 0,
    "deathFromAfar" : 0,
  },
  {
    "name" : "Skeleton Warriors",
    "category" : "Core",
    "aspisArrows" : 0,
    "deathFromAfar" : 0,
    "min" : 20,
    "max" : 60,
  },
  {
    "name" : "Skeleton Archers",
    "category" : "Core",
    "aspisArrows" : 1,
    "deathFromAfar" : 0,
    "min" : 15,
    "max" : 30,
  },
  {
    "name" : "Skeleton Cavalry",
    "category" : "Core",
    "aspisArrows" : 0,
    "deathFromAfar" : 0,
    "min" : 10,
    "max" : 24,
  },
  {
    "name" : "Skeleton Scouts",
    "category" : "Core",
    "aspisArrows" : 1,
    "deathFromAfar" : 0,
    "min" : 5,
    "max" : 10,
  },
  {
    "name" : "Skeleton Chariots",
    "category" : "Core",
    "aspisArrows" : 0,
    "deathFromAfar" : 0,
    "min" : 3,
    "max" : 7,
  },
  {
    "name" : "Necropolis Guard",
    "category" : "Special",
    "aspisArrows" : 0,
    "deathFromAfar" : 0,
    "min" : 15,
    "max" : 40,
  },
  {
    "name" : "Tomb Cataphracts",
    "category" : "Special",
    "aspisArrows" : 0,
    "deathFromAfar" : 0,
    "min" : 3,
    "max" : 5,
  },
  {
    "name" : "Shabtis",
    "category" : "Special",
    "aspisArrows" : 0,
    "deathFromAfar" : 0,
    "min" : 3,
    "max" : 8,
  },
  {
    "name" : "Shabti Archers",
    "category" : "Special",
    "aspisArrows" : 2,
    "deathFromAfar" : 0,
    "min" : 3,
    "max" : 6,
  },
  {
    "name" : "Great Vultures",
    "category" : "Special",
    "aspisArrows" : 0,
    "deathFromAfar" : 0,
    "min" : 3,
    "max" : 9,
  },
  {
    "name" : "Scarab Swarms",
    "category" : "Special",
    "aspisArrows" : 0,
    "deathFromAfar" : 0,
    "min" : 3,
    "max" : 6,
  },
  {
    "name" : "Sand Stalkers",
    "category" : "Special",
    "aspisArrows" : 0,
    "deathFromAfar" : 0,
    "min" : 3,
    "max" : 4,
  },
  {
    "name" : "Casket of Phatep",
    "category" : "Special",
    "aspisArrows" : 0,
    "deathFromAfar" : 0,
  },
  {
    "name" : "Charnel Catapult",
    "category" : "Special",
    "aspisArrows" : 0,
    "deathFromAfar" : 1,
  },
  {
    "name" : "Sand Scorpion",
    "category" : "Entombed",
    "aspisArrows" : 0,
    "deathFromAfar" : 0,
  },
  {
    "name" : "Battle Sphinx",
    "category" : "Mason's Menagerie",
    "aspisArrows" : 0,
    "deathFromAfar" : 0,
  },
  {
    "name" : "Dread Sphinx",
    "category" : "Mason's Menagerie",
    "aspisArrows" : 0,
    "deathFromAfar" : 0,
  },
  {
    "name" : "Tomb Reapers",
    "category" : "Mason's Menagerie",
    "aspisArrows" : 0,
    "deathFromAfar" : 0,
    "min" : 2,
    "max" : 4,
  },
  {
    "name" : "Colossus",
    "category" : "Mason's Menagerie",
    "aspisArrows" : 0,
    "deathFromAfar" : 0,
  },
];

// VC
const VC = [
  {
    "name" : "Lady Chryselie",
    "category" : "Characters",
  },
  {
    "name" : "The Collective of Varyag",
    "category" : "Characters",
  },
  {
    "name" : "Vampire Count",
    "category" : "Characters",
  },
  {
    "name" : "Vampire Courtier",
    "category" : "Characters",
  },
  {
    "name" : "Necromancer",
    "category" : "Characters",
  },
  {
    "name" : "Barrow King",
    "category" : "Characters",
  },
  {
    "name" : "Banshee",
    "category" : "Characters",
  },
  {
    "name" : "Zombies",
    "category" : "Core",
    "min" : 20,
    "max" : 80,
  },
  {
    "name" : "Skeletons",
    "category" : "Core",
    "min" : 20,
    "max" : 60,
  },
  {
    "name" : "Ghouls",
    "category" : "Core",
    "min" : 15,
    "max" : 40,
  },
  {
    "name" : "Bat Swarms",
    "category" : "Core",
    "min" : 3,
    "max" : 6,
  },
  {
    "name" : "Dire Wolves",
    "category" : "Core",
    "min" : 8,
    "max" : 15,
  },
  {
    "name" : "Great Bats",
    "category" : "Special",
    "min" : 2,
    "max" : 9,
  },
  {
    "name" : "Ghasts",
    "category" : "Special",
    "min" : 3,
    "max" : 8,
  },
  {
    "name" : "Barrow Guard",
    "category" : "Special",
    "min" : 15,
    "max" : 40,
  },
  {
    "name" : "Barrow Knights",
    "category" : "Special",
    "min" : 5,
    "max" : 15,
  },
  {
    "name" : "Cadaver Wagon",
    "category" : "Special",
  },
  {
    "name" : "Dark Coach",
    "category" : "Special",
  },
  {
    "name" : "Court of the Damned",
    "category" : "Special",
  },
  {
    "name" : "Altar of Undeath",
    "category" : "Special",
  },
  {
    "name" : "Phantom Hosts",
    "category" : "The Suffering",
    "min" : 3,
    "max" : 6,
  },
  {
    "name" : "Wraiths",
    "category" : "The Suffering",
    "min" : 5,
    "max" : 10,
  },
  {
    "name" : "Spectral Hunters",
    "category" : "The Suffering",
    "min" : 5,
    "max" : 10,
  },
  {
    "name" : "Vampire Knights",
    "category" : "Swift Death",
    "min" : 3,
    "max" : 6,
  },
  {
    "name" : "Vampire Spawn",
    "category" : "Swift Death",
    "min" : 3,
    "max" : 6,
  },
  {
    "name" : "Varkolak",
    "category" : "Swift Death",
  },
  {
    "name" : "Winged Reapers",
    "category" : "Swift Death",
    "min" : 2,
    "max" : 4,
  },
  {
    "name" : "Shrieking Horror",
    "category" : "Swift Death",
  },
];

// VS
const VS = [
  {
    "name" : "Professor Mauss",
    "category" : "Characters",
    "experimentalWeapon" : 0,
  },
  {
    "name" : "The Shadowslice Stalker",
    "category" : "Characters",
    "experimentalWeapon" : 0,
  },
  {
    "name" : "Ruinous Dictator",
    "category" : "Characters",
    "experimentalWeapon" : 0,
  },
  {
    "name" : "Vermin Senator",
    "category" : "Characters",
    "experimentalWeapon" : 0
  },
  {
    "name" : "Bloodfur Legate",
    "category" : "Characters",
    "experimentalWeapon" : 0
  },
  {
    "name" : "House Prefect",
    "category" : "Characters",
    "experimentalWeapon" : 0
  },
  {
    "name" : "Swarm Priest",
    "category" : "Characters",
    "experimentalWeapon" : 0
  },
  {
    "name" : "Duskblade Assassin",
    "category" : "Characters",
    "experimentalWeapon" : 0
  },
  {
    "name" : "Vermin Slingers",
    "category" : "Core",
    "experimentalWeapon" : 0,
    "min" : 20,
    "max" : 30,
  },
  {
    "name" : "Vermin Legionaries",
    "category" : "Core",
    "experimentalWeapon" : 0,
    "min" : 25,
    "max" : 60,
  },
  {
    "name" : "Blackfur Veterans",
    "category" : "Core",
    "experimentalWeapon" : 0,
    "min" : 20,
    "max" : 40,
  },
  {
    "name" : "Vermin Slaves",
    "category" : "Core",
    "experimentalWeapon" : 0,
    "min" : 30,
    "max" : 60,
  },
  {
    "name" : "Plague Cultists",
    "category" : "Core",
    "experimentalWeapon" : 0,
    "min" : 20,
    "max" : 40,
  },
  {
    "name" : "Plague Disciples",
    "category" : "Core",
    "experimentalWeapon" : 0,
    "min" : 15,
    "max" : 40,
  },
  {
    "name" : "Giant Rats",
    "category" : "Core",
    "experimentalWeapon" : 0,
    "min" : 10,
    "max" : 30,
  },
  {
    "name" : "Fire Rats",
    "category" : "Special",
    "experimentalWeapon" : 0,
    "min" : 10,
    "max" : 20,
  },
  {
    "name" : "Bloodfur Praetorians",
    "category" : "Special",
    "experimentalWeapon" : 0,
    "min" : 20,
    "max" : 40,
  },
  {
    "name" : "Rat Swarm",
    "category" : "Special",
    "experimentalWeapon" : 0,
    "min" : 3,
    "max" : 6,
  },
  {
    "name" : "Vermin Brutes",
    "category" : "Special",
    "experimentalWeapon" : 0,
    "bruteForce" : 1,
    "min" : 6,
    "max" : 12,
  },
  {
    "name" : "Gladiator Brutes",
    "category" : "Special",
    "experimentalWeapon" : 0,
    "bruteForce" : 1,
    "min" : 3,
    "max" : 6,
  },
  {
    "name" : "Legionary Drill Team",
    "category" : "Special",
    "experimentalWeapon" : 0
  },
  {
    "name" : "Shadowfur Stalkers",
    "category" : "Special",
    "experimentalWeapon" : 0,
    "min" : 10,
    "max" : 15,
  },
  {
    "name" : "Doomspark Device",
    "category" : "Special",
    "experimentalWeapon" : 0
  },
  {
    "name" : "Thunder Brutes",
    "category" : "Special",
    "experimentalWeapon" : 0,
    "bruteForce" : 1,
    "min" : 3,
    "max" : 6,
  },
  {
    "name" : "Ignifier Grenadiers",
    "category" : "Special",
    "experimentalWeapon" : 0,
    "min": 5,
    "max": 10,
  },
  {
    "name" : "Experimental Weapon Teams",
    "category" : "Special",
    "experimentalWeapon" : 1,
    "min" : 3,
    "max" : 6,
  },
  {
    "name" : "Vermin Artillery",
    "category" : "Special",
    "experimentalWeapon" : 0
  },
  {
    "name" : "Stygian Earthbreaker",
    "category" : "Bread and Games",
    "experimentalWeapon" : 0
  },
  {
    "name" : "Dreadmill Chariots",
    "category" : "Bread and Games",
    "experimentalWeapon" : 0,
    "min" : 1,
    "max" : 3,
  },
  {
    "name" : "Arena Beast",
    "category" : "Bread and Games",
    "experimentalWeapon" : 0
  },

];

// WDG
const WDG = [
    {
    "name" : "Klaas, the Giving",
    "category" : "Characters",
    "legendaryBeast" : 3
  },
  {
    "name" : "Ook, the Ape King",
    "category" : "Characters",
    "legendaryBeast" : 2
  },
  {
    "name" : "Exalted Herald",
    "category" : "Characters",
    "legendaryBeast" : 3,
  },
  {
    "name" : "Chosen Lord",
    "category" : "Characters",
    "legendaryBeast" : 0
  },
  {
    "name" : "Doomlord",
    "category" : "Characters",
    "legendaryBeast" : 0
  },
  {
    "name" : "Sorcerer",
    "category" : "Characters",
    "legendaryBeast" : 0
  },
  {
    "name" : "Barbarian Chief",
    "category" : "Characters",
    "legendaryBeast" : 0
  },
  {
    "name" : "Feldrak Ancestor",
    "category" : "Characters",
    "legendaryBeast" : 2
  },
  {
    "name" : "Warriors",
    "category" : "Core",
    "legendaryBeast" : 0,
    "min" : 10,
    "max" : 25,
  },
  {
    "name" : "Fallen",
    "category" : "Core",
    "legendaryBeast" : 0,
    "min" : 5,
    "max" : 15,

  },
  {
    "name" : "Barbarians",
    "category" : "Core",
    "legendaryBeast" : 0,
    "min" : 15,
    "max" : 40,

  },
  {
    "name" : "Barbarian Horsemen",
    "category" : "Core",
    "legendaryBeast" : 0,
    "min" : 5,
    "max" : 15,

  },
  {
    "name" : "Warhounds",
    "category" : "Special",
    "conditionalCore" : 8,
    "legendaryBeast" : 0,
    "min" : 5,
    "max" : 15,

  },
  {
    "name" : "Warrior Knights",
    "category" : "Special",
    "legendaryBeast" : 0,
    "min" : 5,
    "max" : 10,

  },
  {
    "name" : "Warrior Chariot",
    "category" : "Special",
    "legendaryBeast" : 0
  },
  {
    "name" : "Chosen",
    "category" : "Special",
    "legendaryBeast" : 0,
    "min" : 5,
    "max" : 10,

  },
  {
    "name" : "Chosen Knights",
    "category" : "Special",
    "legendaryBeast" : 0,
    "min" : 3,
    "max" : 4,

  },
  {
    "name" : "Chosen Chariot",
    "category" : "Special",
    "legendaryBeast" : 0
  },
  {
    "name" : "Chimera",
    "category" : "Special",
    "legendaryBeast" : 1
  },
  {
    "name" : "Wretched Ones",
    "category" : "Special",
    "legendaryBeast" : 0,
    "min" : 1,
    "max" : 6,

  },
  {
    "name" : "Forsworn",
    "category" : "Special",
    "legendaryBeast" : 0,
    "min" : 3,
    "max" : 9,

  },
  {
    "name" : "Feldraks",
    "category" : "Special",
    "legendaryBeast" : 0,
    "min" : 3,
    "max" : 5,
  },
  {
    "name" : "Battleshrine",
    "category" : "Special",
    "legendaryBeast" : 0
  },
  {
    "name" : "Flayers",
    "category" : "Special",
    "legendaryBeast" : 0,
    "min" : 5,
    "max" : 10,
  },
  {
    "name" : "Hellmaw",
    "category" : "Special",
    "legendaryBeast" : 0
  },
  {
    "name" : "Forsaken One",
    "category" : "Special",
    "legendaryBeast" : 2
  },
  {
    "name" : "Marauding Giant",
    "category" : "Special",
    "legendaryBeast" : 1
  },
  {
    "name" : "Feldrak Elder",
    "category" : "Special",
    "legendaryBeast" : 2
  },
];

// exports
module.exports = {
  BH,
  DE,
  DH,
  DL,
  EoS,
  HE,
  ID,
  KoE,
  OK,
  OnG,
  SA,
  SE,
  UD,
  VC,
  VS,
  WDG
};
