"use strict";

//BH
const BH = [
  {
    "name" : "Wildhorn Lord",
    "category" : "Characters",
    "sticksandstones" : 0,
    "bigrocks" : 0,
  },
  {
    "name" : "wildhorn chieftain",
    "category" : "Characters",
    "sticksandstones" : 0,
    "bigrocks" : 0,
  },
  {
    "name" : "soothsayer",
    "category" : "Characters",
    "sticksandstones" : 0,
    "bigrocks" : 0,
  },
  {
    "name" : "centaur chieftain",
    "category" : "Characters",
    "sticksandstones" : 0,
    "bigrocks" : 0,
  },
  {
    "name" : "minotaur warlord",
    "category" : "Characters",
    "sticksandstones" : 0,
    "bigrocks" : 0,
  },
  {
    "name" : "minotaur chieftain",
    "category" : "Characters",
    "sticksandstones" : 0,
    "bigrocks" : 0,
  },
  {
    "name" : "wildhorn herd",
    "category" : "Core",
    "sticksandstones" : 0,
    "bigrocks" : 0,
    "min" : 15,
    "max" : 50,
  },
  {
    "name" : "mongrel herd",
    "category" : "Core",
    "sticksandstones" : 0,
    "bigrocks" : 0,
    "min" : 25,
    "max" : 50,
  },
  {
    "name" : "mongrel raiders",
    "category" : "Core",
    "sticksandstones" : 0,
    "bigrocks" : 0,
    "min" : 10,
    "max" : 20,
  },
  {
    "name" : "feral hounds",
    "category" : "Special",
    "conditionalCore" : 8,
    "sticksandstones" : 0,
    "bigrocks" : 0,
    "min" : 5,
    "max" : 15,
  },
  {
    "name" : "longhorn herd",
    "category" : "Special",
    "sticksandstones" : 0,
    "bigrocks" : 0,
    "min" : 10,
    "max" : 30,
  },
  {
    "name" : "minotaurs",
    "category" : "Special",
    "sticksandstones" : 0,
    "bigrocks" : 0,
    "min" : 3,
    "max" : 10,
  },
  {
    "name" : "centaurs",
    "category" : "Special",
    "sticksandstones" : 0,
    "bigrocks" : 0,
    "min" : 5,
    "max" : 15,
  },
  {
    "name" : "raiding chariots",
    "category" : "Special",
    "conditionalCore" : 3,
    "sticksandstones" : 0,
    "bigrocks" : 0,
    "min" : 1,
    "max" : 3,
  },
  {
    "name" : "razortusk herd",
    "category" : "Special",
    "sticksandstones" : 0,
    "bigrocks" : 0,
    "min" : 3,
    "max" : 10,
  },
  {
    "name" : "razortusk chariot",
    "category" : "Special",
    "sticksandstones" : 0,
    "bigrocks" : 0,
  },
  {
    "name" : "briar beast",
    "category" : "Special",
    "sticksandstones" : 0,
    "bigrocks" : 0,
  },
  {
    "name" : "gargoyles",
    "category" : "Special",
    "sticksandstones" : 0,
    "bigrocks" : 0,
    "min" : 5,
    "max" : 10,
  },
  {
    "name" : "cyclops",
    "category" : "terrors of the wild",
    "sticksandstones" : 0,
    "bigrocks" : 1,
  },
  {
    "name" : "gortach",
    "category" : "terrors of the wild",
    "sticksandstones" : 0,
    "bigrocks" : 0,
  },
  {
    "name" : "jabberwock",
    "category" : "terrors of the wild",
    "sticksandstones" : 0,
    "bigrocks" : 0,
  },
  {
    "name" : "beast giant",
    "category" : "terrors of the wild",
    "sticksandstones" : 0,
    "bigrocks" : 0,
  },
];

// DE
const DE = [
  {
    "name" : "Dread Prince",
    "category" : "Characters",
    "raiders" : 0,
    "boltThrowers" : 0,
  },
  {
    "name" : "Silexian Officer",
    "category" : "Characters",
    "raiders" : 0,
    "boltThrowers" : 0,
  },
  {
    "name" : "Temple Exarch",
    "category" : "Characters",
    "raiders" : 0,
    "boltThrowers" : 0,
  },
  {
    "name" : "Sanctioned Warlock",
    "category" : "Characters",
    "raiders" : 0,
    "boltThrowers" : 0,
  },
  {
    "name" : "Silent Assassin",
    "category" : "Characters",
    "raiders" : 0,
    "boltThrowers" : 0,
  },
  {
    "name" : "Silexian Spears",
    "category" : "Core",
    "raiders" : 0,
    "boltThrowers" : 0,
    "min" : 15,
    "max" : 35,
  },
  {
    "name" : "Silexian Auxiliaries",
    "category" : "Core",
    "raiders" : 1,
    "boltThrowers" : 0,
    "min" : 10,
    "max" : 25,
  },
  {
    "name" : "Temple Militants",
    "category" : "Core",
    "raiders" : 0,
    "boltThrowers" : 0,
    "min" : 10,
    "max" : 25,
  },
  {
    "name" : "Corsairs",
    "category" : "Core",
    "raiders" : 0,
    "boltThrowers" : 0,
    "min" : 10,
    "max" : 30,
  },
  {
    "name" : "Shadow Riders",
    "category" : "Core",
    "raiders" : 0,
    "boltThrowers" : 0,
    "min" : 5,
    "max" : 10,
  },
  {
    "name" : "Dread Acolytes",
    "category" : "Special",
    "raiders" : 0,
    "boltThrowers" : 0,
    "min" : 5,
    "max" : 12,
  },
  {
    "name" : "Dread Knights",
    "category" : "Special",
    "raiders" : 0,
    "boltThrowers" : 0,
    "min" : 5,
    "max" : 10,
  },
  {
    "name" : "Obsidian Guard",
    "category" : "Special",
    "raiders" : 0,
    "boltThrowers" : 0,
    "min" : 10,
    "max" : 25,
  },
  {
    "name" : "Judicators",
    "category" : "Special",
    "raiders" : 0,
    "boltThrowers" : 0,
    "min" : 10,
    "max" : 25,
  },
  {
    "name" : "Harpies",
    "category" : "Special",
    "raiders" : 0,
    "boltThrowers" : 0,
    "min" : 5,
    "max" : 12,
  },
  {
    "name" : "Gorgons",
    "category" : "Special",
    "raiders" : 0,
    "boltThrowers" : 0,
    "min" : 2,
    "max" : 4,
  },
  {
    "name" : "Thunder Pack",
    "category" : "Special",
    "raiders" : 0,
    "boltThrowers" : 0,
    "min" : 3,
    "max" : 6,
  },
  {
    "name" : "Raptor Chariot",
    "category" : "Special",
    "raiders" : 0,
    "boltThrowers" : 0,
  },
  {
    "name" : "Divine Altar",
    "category" : "Special",
    "raiders" : 0,
    "boltThrowers" : 0,
  },
  {
    "name" : "Hunting Chariot",
    "category" : "Special",
    "raiders" : 0,
    "boltThrowers" : 1,
  },
  {
    "name" : "Repeater Battery",
    "category" : "Special",
    "raiders" : 0,
    "boltThrowers" : 1,
  },
  {
    "name" : "Black Cloaks",
    "category" : "Special",
    "raiders" : 0,
    "boltThrowers" : 0,
    "min" : 5,
    "max" : 10,
  },
  {
    "name" : "Kraken",
    "category" : "the menagerie",
    "raiders" : 0,
    "boltThrowers" : 0,
  },
  {
    "name" : "Hydra",
    "category" : "the menagerie",
    "raiders" : 0,
    "boltThrowers" : 0,
  },
  {
    "name" : "Mist Leviathan",
    "category" : "the menagerie",
    "raiders" : 0,
    "boltThrowers" : 0,
  },
];

// DH
const DH = [
  {
    "name" : "king",
    "category" : "Characters",
    "clansThunder" : 0,
    "enginesOfWar" : 0,
  },
  {
    "name" : "thane",
    "category" : "Characters",
    "clansThunder" : 0,
    "enginesOfWar" : 0,
  },
  {
    "name" : "runic smith",
    "category" : "Characters",
    "clansThunder" : 0,
    "enginesOfWar" : 0,
  },
  {
    "name" : "engineer",
    "category" : "Characters",
    "clansThunder" : 0,
    "enginesOfWar" : 0,
  },
  {
    "name" : "dragon seeker",
    "category" : "Characters",
    "clansThunder" : 0,
    "enginesOfWar" : 0,
  },
  {
    "name" : "clan warriors",
    "category" : "Core",
    "clansThunder" : 0,
    "enginesOfWar" : 0,
    "min" : 15,
    "max" : 40,
  },
  {
    "name" : "greybeards",
    "category" : "Core",
    "clansThunder" : 0,
    "enginesOfWar" : 0,
    "min" : 10,
    "max" : 25,
  },
  {
    "name" : "clan marksmen",
    "category" : "Core",
    "clansThunder" : 0,
    "enginesOfWar" : 0,
    "min" : 10,
    "max" : 20,
  },
  {
    "name" : "king's guard",
    "category" : "Special",
    "clansThunder" : 0,
    "enginesOfWar" : 0,
    "min" : 15,
    "max" : 25,
  },
  {
    "name" : "deep watch",
    "category" : "Special",
    "clansThunder" : 0,
    "enginesOfWar" : 0,
    "min" : 15,
    "max" : 25,
  },
  {
    "name" : "seekers",
    "category" : "Special",
    "clansThunder" : 0,
    "enginesOfWar" : 0,
    "min" : 8,
    "max" : 25,
  },
  {
    "name" : "brothers of vengeance",
    "category" : "Special",
    "clansThunder" : 0,
    "enginesOfWar" : 0,
    "min" : 8,
    "max" : 15,
  },
  {
    "name" : "vengeance seeker",
    "category" : "Special",
    "clansThunder" : 0,
    "enginesOfWar" : 0,
  },
  {
    "name" : "hold guardians",
    "category" : "Special",
    "clansThunder" : 0,
    "enginesOfWar" : 0,
    "min" : 3,
    "max" : 6,
  },
  {
    "name" : "grudge buster",
    "category" : "Special",
    "clansThunder" : 0,
    "enginesOfWar" : 0,
  },
  {
    "name" : "miners",
    "category" : "Special",
    "clansThunder" : 0,
    "enginesOfWar" : 0,
    "min" : 10,
    "max" : 20,
  },
  {
    "name" : "anvil of power",
    "category" : "Special",
    "clansThunder" : 0,
    "enginesOfWar" : 0,
  },
  {
    "name" : "rangers",
    "category" : "Special",
    "clansThunder" : 0,
    "enginesOfWar" : 0,
    "min" : 10,
    "max" : 20,
  },
  {
    "name" : "forge wardens",
    "category" : "Special",
    "clansThunder" : 0,
    "enginesOfWar" : 0,
    "min" : 10,
    "max" : 16,
  },
  {
    "name" : "steam copters",
    "category" : "Special",
    "clansThunder" : 0,
    "enginesOfWar" : 0,
    "min" : 1,
    "max" : 2,
  },
  {
    "name" : "field artillery",
    "category" : "Special",
    "clansThunder" : 0,
    "enginesOfWar" : 1,
  },
];

// DL
const DL = [
  {
    "name" : "harbinger of father chaos",
    "category" : "Characters",
    "magicShooting" : 0,
  },
  {
    "name" : "kuulima's deceiver",
    "category" : "Characters",
    "magicShooting" : 0,
  },
  {
    "name" : "maw of akaan",
    "category" : "Characters",
    "magicShooting" : 0,
  },
  {
    "name" : "miser of sugulag",
    "category" : "Characters",
    "magicShooting" : 0,
  },
  {
    "name" : "courtesan of cibaresh",
    "category" : "Characters",
    "magicShooting" : 0,
  },
  {
    "name" : "omen of savar",
    "category" : "Characters",
    "magicShooting" : 0,
  },
  {
    "name" : "sentinel of nukuja",
    "category" : "Characters",
    "magicShooting" : 0,
  },
  {
    "name" : "vanadra's scourge",
    "category" : "Characters",
    "magicShooting" : 0,
  },
  {
    "name" : "imps",
    "category" : "Core",
    "magicShooting" : 1,
    "min" : 10,
    "max" : 25,
  },
  {
    "name" : "succubi",
    "category" : "Core",
    "magicShooting" : 0,
    "min" : 10,
    "max" : 25,
  },
  {
    "name" : "lemures",
    "category" : "Core",
    "magicShooting" : 0,
    "min" : 10,
    "max" : 25,
  },
  {
    "name" : "myrmidons",
    "category" : "Core",
    "magicShooting" : 0,
    "min" : 10,
    "max" : 25,
  },
  {
    "name" : "eidolons",
    "category" : "Special",
    "magicShooting" : 3,
    "min" : 5,
    "max" : 10,
  },
  {
    "name" : "hellhounds",
    "category" : "Special",
    "magicShooting" : 0,
    "min" : 5,
    "max" : 15,
  },
  {
    "name" : "threshing engine",
    "category" : "Special",
    "magicShooting" : 0,
    "min" : 1,
    "max" : 3,
  },
  {
    "name" : "titanslayer chariot",
    "category" : "Special",
    "magicShooting" : 0,
  },
  {
    "name" : "mageblight gremlins",
    "category" : "Special",
    "magicShooting" : 0,
    "min" : 3,
    "max" : 6,
  },
  {
    "name" : "clawed fiends",
    "category" : "Special",
    "magicShooting" : 0,
    "min" : 3,
    "max" : 8,
  },
  {
    "name" : "hoarders",
    "category" : "Special",
    "magicShooting" : 0,
    "min" : 3,
    "max" : 6,
  },
  {
    "name" : "succubi tempters",
    "category" : "Special",
    "magicShooting" : 0,
    "min" : 5,
    "max" : 10,
  },
  {
    "name" : "blazing glory",
    "category" : "Special",
    "magicShooting" : 0,
  },
  {
    "name" : "hope harvester",
    "category" : "Special",
    "magicShooting" : 5,
  },
  {
    "name" : "brazen beasts",
    "category" : "Special",
    "magicShooting" : 0,
    "min" : 3,
    "max" : 5,
  },
  {
    "name" : "furies",
    "category" : "aves",
    "magicShooting" : 0,
    "min" : 5,
    "max" : 15,
  },
  {
    "name" : "veil serpents",
    "category" : "aves",
    "magicShooting" : 0,
    "min" : 3,
    "max" : 6,
  },
  {
    "name" : "bloat flies",
    "category" : "aves",
    "magicShooting" : 0,
    "min" : 3,
    "max" : 5,
  },
];

// EoS
const EoS = [
  {
    "name" : "marshal",
    "category" : "Characters",
    "imperialAuxiliaries" : 0,
    "imperialArmory" : 0,
  },
  {
    "name" : "knight commander",
    "category" : "Characters",
    "imperialAuxiliaries" : 0,
    "imperialArmory" : 0,
  },
  {
    "name" : "battlefield wizard",
    "category" : "Characters",
    "imperialAuxiliaries" : 0,
    "imperialArmory" : 0,
  },
  {
    "name" : "prelate",
    "category" : "Characters",
    "imperialAuxiliaries" : 0,
    "imperialArmory" : 0,
  },
  {
    "name" : "artificer",
    "category" : "Characters",
    "imperialAuxiliaries" : 0,
    "imperialArmory" : 0,
  },
  {
    "name" : "inquisitor",
    "category" : "Characters",
    "imperialAuxiliaries" : 0,
    "imperialArmory" : 0,
  },
  {
    "name" : "state infantry",
    "category" : "Core",
    "imperialAuxiliaries" : 0,
    "imperialArmory" : 0,
    "min" : 20,
    "max" : 40,
  },
  {
    "name" : "state detachment",
    "category" : "Core",
    "imperialAuxiliaries" : 0,
    "imperialArmory" : 0,
    "min" : 15,
    "max" : 20,
  },
  {
    "name" : "state detatchment",
    "category" : "Core",
    "imperialAuxiliaries" : 0,
    "imperialArmory" : 0,
    "min" : 15,
    "max" : 20,
  },
  {
    "name" : "state marksmen",
    "category" : "Core",
    "imperialAuxiliaries" : 1,
    "imperialArmory" : 0,
    "min" : 15,
    "max" : 20,
  },
  {
    "name" : "light infantry",
    "category" : "Core",
    "imperialAuxiliaries" : 1,
    "imperialArmory" : 0,
    "min" : 15,
    "max" : 20,
  },
  {
    "name" : "local militia",
    "category" : "Core",
    "imperialAuxiliaries" : 1,
    "imperialArmory" : 0,
    "min" : 15,
    "max" : 25,
  },
  {
    "name" : "electoral cavalry",
    "category" : "Core",
    "imperialAuxiliaries" : 0,
    "imperialArmory" : 0,
    "min" : 8,
    "max" : 20,
  },
  {
    "name" : "knightly orders",
    "category" : "Core",
    "imperialAuxiliaries" : 0,
    "imperialArmory" : 0,
    "min" : 5,
    "max" : 15,
  },
  {
    "name" : "imperial guard",
    "category" : "Special",
    "imperialAuxiliaries" : 0,
    "imperialArmory" : 0,
    "min" : 15,
    "max" : 30,
  },
  {
    "name" : "imperial detachment",
    "category" : "Special",
    "imperialAuxiliaries" : 0,
    "imperialArmory" : 0,
    "min" : 15,
    "max" : 15,
  },
  {
    "name" : "knights of the sun griffon",
    "category" : "Special",
    "imperialAuxiliaries" : 0,
    "imperialArmory" : 0,
    "min" : 3,
    "max" : 5,
  },
  {
    "name" : "arcane engine",
    "category" : "Special",
    "imperialAuxiliaries" : 0,
    "imperialArmory" : 0,
  },
  {
    "name" : "imperial rangers",
    "category" : "Special",
    "imperialAuxiliaries" : 1,
    "imperialArmory" : 0,
    "min" : 8,
    "max" : 15,
  },
  {
    "name" : "reiters",
    "category" : "Special",
    "imperialAuxiliaries" : 1,
    "imperialArmory" : 0,
    "min" : 5,
    "max" : 10,
  },
  {
    "name" : "blackpowder artillery",
    "category" : "Special",
    "imperialAuxiliaries" : 0,
    "imperialArmory" : 1,
  },
  {
    "name" : "flagellants",
    "category" : "sunna's fury",
    "imperialAuxiliaries" : 0,
    "imperialArmory" : 0,
    "min" : 15,
    "max" : 30,
  },
  {
    "name" : "steam tank",
    "category" : "sunna's fury",
    "imperialAuxiliaries" : 0,
    "imperialArmory" : 1,
  },
];

// HE
const HE = [
  {
    "name" : "high prince",
    "category" : "Characters",
    "queensBows" : 0,
    "navalOrdnance" : 0,
    "ancientAllies" : 0,
  },
  {
    "name" : "commander",
    "category" : "Characters",
    "queensBows" : 0,
    "navalOrdnance" : 0,
    "ancientAllies" : 0,
  },
  {
    "name" : "mage",
    "category" : "Characters",
    "queensBows" : 0,
    "navalOrdnance" : 0,
    "ancientAllies" : 0,
  },
  {
    "name" : "citizen archers",
    "category" : "Core",
    "queensBows" : 1,
    "navalOrdnance" : 0,
    "ancientAllies" : 0,
    "min" : 15,
    "max" : 30,
  },
  {
    "name" : "citizen spears",
    "category" : "Core",
    "queensBows" : 0,
    "navalOrdnance" : 0,
    "ancientAllies" : 0,
    "min" : 20,
    "max" : 40,
  },
  {
    "name" : "sea guard",
    "category" : "Core",
    "queensBows" : 1,
    "navalOrdnance" : 0,
    "ancientAllies" : 0,
    "min" : 15,
    "max" : 30,
  },
  {
    "name" : "highborn lancers",
    "category" : "Core",
    "queensBows" : 0,
    "navalOrdnance" : 0,
    "ancientAllies" : 0,
    "min" : 5,
    "max" : 15,
  },
  {
    "name" : "erlein reavers",
    "category" : "Core",
    "queensBows" : 0,
    "navalOrdnance" : 0,
    "ancientAllies" : 0,
    "min" : 5,
    "max" : 10,
  },
  {
    "name" : "sword masters",
    "category" : "Special",
    "queensBows" : 0,
    "navalOrdnance" : 0,
    "ancientAllies" : 0,
    "min" : 10,
    "max" : 25,
  },
  {
    "name" : "lion guard",
    "category" : "Special",
    "queensBows" : 0,
    "navalOrdnance" : 0,
    "ancientAllies" : 0,
    "min" : 10,
    "max" : 25,
  },
  {
    "name" : "flame wardens",
    "category" : "Special",
    "queensBows" : 0,
    "navalOrdnance" : 0,
    "ancientAllies" : 0,
    "min" : 10,
    "max" : 25,
  },
  {
    "name" : "knights of rymâ",
    "category" : "Special",
    "queensBows" : 0,
    "navalOrdnance" : 0,
    "ancientAllies" : 0,
    "min" : 5,
    "max" : 10,
  },
  {
    "name" : "reaver chariots",
    "category" : "Special",
    "queensBows" : 0,
    "navalOrdnance" : 0,
    "ancientAllies" : 0,
    "min" : 2,
    "max" : 3,
  },
  {
    "name" : "lion chariot",
    "category" : "Special",
    "queensBows" : 0,
    "navalOrdnance" : 0,
    "ancientAllies" : 0,
  },
  {
    "name" : "giant eagles",
    "category" : "Special",
    "queensBows" : 0,
    "navalOrdnance" : 0,
    "ancientAllies" : 0,
    "min" : 1,
    "max" : 5,
  },
  {
    "name" : "initiate of the fiery heart",
    "category" : "Special",
    "queensBows" : 0,
    "navalOrdnance" : 0,
    "ancientAllies" : 1,
  },
  {
    "name" : "phoenix",
    "category" : "Special",
    "queensBows" : 0,
    "navalOrdnance" : 0,
    "ancientAllies" : 1,
  },
  {
    "name" : "sea guard reaper",
    "category" : "Special",
    "queensBows" : 0,
    "navalOrdnance" : 1,
    "ancientAllies" : 0,
  },
  {
    "name" : "sky sloop",
    "category" : "Special",
    "queensBows" : 0,
    "navalOrdnance" : 1,
    "ancientAllies" : 0,
  },
  {
    "name" : "queen's guard",
    "category" : "Special",
    "queensBows" : 1,
    "navalOrdnance" : 0,
    "ancientAllies" : 0,
    "min" : 10,
    "max" : 20,
  },
  {
    "name" : "grey watchers",
    "category" : "Special",
    "queensBows" : 1,
    "navalOrdnance" : 0,
    "ancientAllies" : 0,
    "min" : 5,
    "max" : 10,
  },
];

// ID
const ID = [
  {
    "name" : "overlord",
    "category" : "Characters",
    "firesOfIndustry" : 0,
    "blackPowder" : 0,
  },
  {
    "name" : "prophet",
    "category" : "Characters",
    "firesOfIndustry" : 0,
    "blackPowder" : 0,
  },
  {
    "name" : "vizier",
    "category" : "Characters",
    "firesOfIndustry" : 0,
    "blackPowder" : 0,
  },
  {
    "name" : "taurukh commissioner",
    "category" : "Characters",
    "firesOfIndustry" : 0,
    "blackPowder" : 0,
  },
  {
    "name" : "vassal conjurer",
    "category" : "Characters",
    "firesOfIndustry" : 0,
    "blackPowder" : 0,
  },
  {
    "name" : "lamassu scholar",
    "category" : "Characters",
    "firesOfIndustry" : 0,
    "blackPowder" : 0,
  },
  {
    "name" : "infernal warriors",
    "category" : "Core",
    "firesOfIndustry" : 0,
    "blackPowder" : 0,
    "min" : 20,
    "max" : 40,
  },
  {
    "name" : "citadel guard",
    "category" : "Core",
    "firesOfIndustry" : 0,
    "blackPowder" : 0,
    "min" : 15,
    "max" : 25,
  },
  {
    "name" : "vassal levies",
    "category" : "Core",
    "firesOfIndustry" : 0,
    "blackPowder" : 0,
    "min" : 20,
    "max" : 40,
  },
  {
    "name" : "shackled slaves",
    "category" : "Core",
    "firesOfIndustry" : 0,
    "blackPowder" : 0,
    "min" : 20,
    "max" : 40,
  },
  {
    "name" : "kadim incarnates",
    "category" : "Special",
    "firesOfIndustry" : 0,
    "blackPowder" : 0,
    "min" : 3,
    "max" : 6,
  },
  {
    "name" : "kadim chariot",
    "category" : "Special",
    "firesOfIndustry" : 0,
    "blackPowder" : 0,
  },
  {
    "name" : "immortals",
    "category" : "Special",
    "firesOfIndustry" : 0,
    "blackPowder" : 0,
    "min" : 15,
    "max" : 25,
  },
  {
    "name" : "disciples of lugar",
    "category" : "Special",
    "firesOfIndustry" : 0,
    "blackPowder" : 0,
    "min" : 15,
    "max" : 25,
  },
  {
    "name" : "taurukh enforcers",
    "category" : "Special",
    "firesOfIndustry" : 0,
    "blackPowder" : 0,
    "min" : 5,
    "max" : 12,
  },
  {
    "name" : "taurukh anointed",
    "category" : "Special",
    "firesOfIndustry" : 0,
    "blackPowder" : 0,
    "min" : 3,
    "max" : 5,
  },
  {
    "name" : "vassal cavalry",
    "category" : "Special",
    "firesOfIndustry" : 0,
    "blackPowder" : 0,
    "min" : 5,
    "max" : 15,
  },
  {
    "name" : "vassal slingshot",
    "category" : "Special",
    "firesOfIndustry" : 0,
    "blackPowder" : 0,
  },
  {
    "name" : "gunnery team",
    "category" : "Special",
    "firesOfIndustry" : 0,
    "blackPowder" : 0,
  },
  {
    "name" : "infernal artillery",
    "category" : "Special",
    "firesOfIndustry" : 0,
    "blackPowder" : 0,
  },
  {
    "name" : "infernal bastion",
    "category" : "Special",
    "firesOfIndustry" : 0,
    "blackPowder" : 0,
  },
  {
    "name" : "infernal engine",
    "category" : "instruments of destruction",
    "firesOfIndustry" : 0,
    "blackPowder" : 0,
  },
  {
    "name" : "kadim titan",
    "category" : "instruments of destruction",
    "firesOfIndustry" : 0,
    "blackPowder" : 0,
  },
  {
    "name" : "citizen giant",
    "category" : "instruments of destruction",
    "firesOfIndustry" : 0,
    "blackPowder" : 0,
  },
];

// KoE
const KoE = [
  {
    "name" : "Damsel",
    "category" : "Characters",
    "gallantry" : 0,
    "smallArmsFire" : 0,
    "siegeEngines" : 0,
  },
  {
    "name" : "Duke",
    "category" : "Characters",
    "gallantry" : 0,
    "smallArmsFire" : 0,
    "siegeEngines" : 0,
  },
  {
    "name" : "Paladin",
    "category" : "Characters",
    "gallantry" : 0,
    "smallArmsFire" : 0,
    "siegeEngines" : 0,
  },
  {
    "name" : "Folk Hero",
    "category" : "Characters",
    "gallantry" : 0,
    "smallArmsFire" : 0,
    "siegeEngines" : 0,
  },
  {
    "name" : "Knights of the Realm",
    "category" : "Core",
    "gallantry" : 0,
    "smallArmsFire" : 0,
    "siegeEngines" : 0,
    "min" : 6,
    "max" : 12,
  },
  {
    "name" : "Hedge Knights",
    "category" : "Core",
    "gallantry" : 2,
    "smallArmsFire" : 0,
    "siegeEngines" : 0,
    "min" : 6,
    "max" : 9,
  },
  {
    "name" : "Mounted Serjeants",
    "category" : "Core",
    "gallantry" : 0,
    "smallArmsFire" : 0,
    "siegeEngines" : 0,
    "min" : 8,
    "max" : 15,
  },
  {
    "name" : "Lowborn Levies",
    "category" : "Core",
    "gallantry" : 0,
    "smallArmsFire" : 0,
    "siegeEngines" : 0,
    "min" : 30,
    "max" : 50,
  },
  {
    "name" : "Lowborn Archers",
    "category" : "Core",
    "gallantry" : 0,
    "smallArmsFire" : 0,
    "siegeEngines" : 0,
    "min" : 15,
    "max" : 30,
  },
  {
    "name" : "Men-at-Arms",
    "category" : "Special",
    "gallantry" : 0,
    "smallArmsFire" : 0,
    "siegeEngines" : 0,
    "min" : 15,
    "max" : 30,
  },
  {
    "name" : "Sacred Reliquary",
    "category" : "Special",
    "gallantry" : 0,
    "smallArmsFire" : 0,
    "siegeEngines" : 0,
  },
  {
    "name" : "Knights of the Court",
    "category" : "Special",
    "gallantry" : 0,
    "smallArmsFire" : 0,
    "siegeEngines" : 0,
    "min" : 6,
    "max" : 12,
  },
  {
    "name" : "Knights Penitent",
    "category" : "Special",
    "gallantry" : 0,
    "smallArmsFire" : 0,
    "siegeEngines" : 0,
    "min" : 3,
    "max" : 9,
  },
  {
    "name" : "Knights of the Quest",
    "category" : "Special",
    "gallantry" : 0,
    "smallArmsFire" : 0,
    "siegeEngines" : 0,
    "min" : 6,
    "max" : 9,
  },
  {
    "name" : "Yeoman Outriders",
    "category" : "Special",
    "gallantry" : 0,
    "smallArmsFire" : 0,
    "siegeEngines" : 0,
    "min" : 5,
    "max" : 15,
  },
  {
    "name" : "Enlisted Outlaws",
    "category" : "Special",
    "gallantry" : 0,
    "smallArmsFire" : 0,
    "siegeEngines" : 0,
    "min" : 10,
    "max" : 15,
  },
  {
    "name" : "Siege Weapon",
    "category" : "Special",
    "gallantry" : 0,
    "smallArmsFire" : 0,
    "siegeEngines" : 1,
  },
  {
    "name" : "Pegasus Knights",
    "category" : "Special",
    "gallantry" : 2,
    "smallArmsFire" : 0,
    "siegeEngines" : 0,
    "min" : 3,
    "max" : 5,
  },
  {
    "name" : "Sky Heralds",
    "category" : "Special",
    "gallantry" : 1,
    "smallArmsFire" : 0,
    "siegeEngines" : 0,
    "min" : 3,
    "max" : 6,
  },
  {
    "name" : "Naiads",
    "category" : "Fey",
    "gallantry" : 0,
    "smallArmsFire" : 0,
    "siegeEngines" : 0,
    "min" : 5,
    "max" : 10,
  },
  {
    "name" : "Friar's Lantern",
    "category" : "Fey",
    "gallantry" : 0,
    "smallArmsFire" : 0,
    "siegeEngines" : 0,
  },
  {
    "name" : "The Lady's Courtier",
    "category" : "Fey",
    "gallantry" : 0,
    "smallArmsFire" : 0,
    "siegeEngines" : 0,
  },
  {
    "name" : "Fey Knight",
    "category" : "Fey",
    "gallantry" : 1,
    "smallArmsFire" : 0,
    "siegeEngines" : 0,
  },
];

// OK
const OK = [
  {
    "name" : "great khan",
    "category" : "Characters",
    "hiredGuns" : 0,
    "powderKeg" : 0,
  },
  {
    "name" : "khan",
    "category" : "Characters",
    "hiredGuns" : 0,
    "powderKeg" : 0,
  },
  {
    "name" : "shaman",
    "category" : "Characters",
    "hiredGuns" : 0,
    "powderKeg" : 0,
  },
  {
    "name" : "mammoth hunter",
    "category" : "Characters",
    "hiredGuns" : 0,
    "powderKeg" : 0,
  },
  {
    "name" : "tribesmen",
    "category" : "Core",
    "hiredGuns" : 0,
    "powderKeg" : 0,
    "min" : 4,
    "max" : 15,
  },
  {
    "name" : "bruisers",
    "category" : "Core",
    "hiredGuns" : 0,
    "powderKeg" : 0,
    "min" : 3,
    "max" : 10,
  },
  {
    "name" : "scraplings",
    "category" : "Core",
    "hiredGuns" : 0,
    "powderKeg" : 0,
    "min" : 20,
    "max" : 60,
  },
  {
    "name" : "sabretooth tigers",
    "category" : "Special",
    "conditionalCore" : 5,
    "hiredGuns" : 0,
    "powderKeg" : 0,
    "min" : 3,
    "max" : 15,
  },
  {
    "name" : "scrapling trappers",
    "category" : "Special",
    "hiredGuns" : 0,
    "powderKeg" : 0,
    "min" : 8,
    "max" : 15,
  },
  {
    "name" : "yetis",
    "category" : "Special",
    "hiredGuns" : 0,
    "powderKeg" : 0,
    "min" : 2,
    "max" : 5,
  },
  {
    "name" : "kin-eater",
    "category" : "Special",
    "hiredGuns" : 0,
    "powderKeg" : 0,
  },
  {
    "name" : "tusker cavalry",
    "category" : "Special",
    "hiredGuns" : 0,
    "powderKeg" : 0,
    "min" : 3,
    "max" : 5,
  },
  {
    "name" : "mercenary veterans",
    "category" : "Special",
    "hiredGuns" : 0,
    "powderKeg" : 0,
    "min" : 3,
    "max" : 9,
  },
  {
    "name" : "mercenary gunners",
    "category" : "Special",
    "hiredGuns" : 0,
    "powderKeg" : 0,
    "min" : 3,
    "max" : 6,
  },
  {
    "name" : "bombardiers",
    "category" : "Special",
    "hiredGuns" : 0,
    "powderKeg" : 0,
    "min" : 3,
    "max" : 8,
  },
  {
    "name" : "thunder cannon",
    "category" : "Special",
    "hiredGuns" : 0,
    "powderKeg" : 1,
  },
  {
    "name" : "scratapult",
    "category" : "Special",
    "hiredGuns" : 0,
    "powderKeg" : 1,
  },
  {
    "name" : "rock aurochs",
    "category" : "chained beasts",
    "hiredGuns" : 0,
    "powderKeg" : 0,
  },
  {
    "name" : "frost mammoth",
    "category" : "chained beasts",
    "hiredGuns" : 0,
    "powderKeg" : 0,
  },
  {
    "name" : "mercenary giant",
    "category" : "chained beasts",
    "hiredGuns" : 0,
    "powderKeg" : 0,
  },
];
// OnG
const OnG = [
  {
    "name" : "Orc Warlord",
    "category" : "Characters",
    "bigAndNasty" : 0,
    "deathFromAbove" : 0,
    "archerBroods" : 0,
  },
  {
    "name" : "Iron Orc Loner",
    "category" : "Characters",
    "bigAndNasty" : 0,
    "deathFromAbove" : 0,
    "archerBroods" : 0,
  },
  {
    "name" : "Brood Alpha",
    "category" : "Characters",
    "bigAndNasty" : 0,
    "deathFromAbove" : 0,
    "archerBroods" : 0,
  },
  {
    "name" : "Orc Shaman",
    "category" : "Characters",
    "bigAndNasty" : 0,
    "deathFromAbove" : 0,
    "archerBroods" : 0,
  },
  {
    "name" : "Goblin Demagogue",
    "category" : "Characters",
    "bigAndNasty" : 0,
    "deathFromAbove" : 0,
    "archerBroods" : 0,
  },
  {
    "name" : "Goblin Witch",
    "category" : "Characters",
    "bigAndNasty" : 0,
    "deathFromAbove" : 0,
    "archerBroods" : 0,
  },
  {
    "name" : "Gogtuk Initiate",
    "category" : "Characters",
    "bigAndNasty" : 0,
    "deathFromAbove" : 0,
    "archerBroods" : 0,
  },
  {
    "name" : "Mad Git",
    "category" : "Characters",
    "bigAndNasty" : 0,
    "deathFromAbove" : 0,
    "archerBroods" : 0,
  },
  {
    "name" : "Goblin Rabble",
    "category" : "Core",
    "bigAndNasty" : 0,
    "deathFromAbove" : 0,
    "archerBroods" : 0,
    "min" : 25,
    "max" : 60,
  },
  {
    "name" : "Goblin Reavers",
    "category" : "Core",
    "bigAndNasty" : 0,
    "deathFromAbove" : 0,
    "archerBroods" : 0,
    "min" : 8,
    "max" : 25,
  },
  {
    "name" : "Feral Orcs",
    "category" : "Core",
    "bigAndNasty" : 0,
    "deathFromAbove" : 0,
    "archerBroods" : 0,
    "min" : 25,
    "max" : 50,
  },
  {
    "name" : "Feral Orc Marauders",
    "category" : "Core",
    "bigAndNasty" : 0,
    "deathFromAbove" : 0,
    "archerBroods" : 0,
    "min" : 10,
    "max" : 25,
  },
  {
    "name" : "Veteran Orcs",
    "category" : "Core",
    "bigAndNasty" : 0,
    "deathFromAbove" : 0,
    "archerBroods" : 0,
    "min" : 20,
    "max" : 40,
  },
  {
    "name" : "Veteran Orc Marauders",
    "category" : "Core",
    "bigAndNasty" : 0,
    "deathFromAbove" : 0,
    "archerBroods" : 0,
    "min" : 5,
    "max" : 15,
  },
  {
    "name" : "Iron Orcs",
    "category" : "Special",
    "bigAndNasty" : 0,
    "deathFromAbove" : 0,
    "archerBroods" : 0,
    "min" : 15,
    "max" : 30,
  },
  {
    "name" : "Iron Orc Chariots",
    "category" : "Special",
    "bigAndNasty" : 0,
    "deathFromAbove" : 0,
    "archerBroods" : 0,
    "min" : 1,
    "max" : 2,
  },
  {
    "name" : "Gogtuk Neophytes",
    "category" : "Special",
    "bigAndNasty" : 0,
    "deathFromAbove" : 0,
    "archerBroods" : 0,
    "min" : 10,
    "max" : 20,
  },
  {
    "name" : "Goblin Chariots",
    "category" : "Special",
    "bigAndNasty" : 0,
    "deathFromAbove" : 0,
    "archerBroods" : 0,
    "min" : 2,
    "max" : 3,
  },
  {
    "name" : "Grotlings",
    "category" : "Special",
    "bigAndNasty" : 0,
    "deathFromAbove" : 0,
    "archerBroods" : 0,
    "min" : 3,
    "max" : 6,
  },
  {
    "name" : "Grotling Scrap Wagon",
    "category" : "Special",
    "bigAndNasty" : 0,
    "deathFromAbove" : 0,
    "archerBroods" : 0,
  },
  {
    "name" : "Gnashers",
    "category" : "Special",
    "bigAndNasty" : 0,
    "deathFromAbove" : 0,
    "archerBroods" : 0,
    "min" : 15,
    "max" : 40,
  },
  {
    "name" : "Gnasher Dashers",
    "category" : "Special",
    "bigAndNasty" : 0,
    "deathFromAbove" : 0,
    "archerBroods" : 0,
    "min" : 10,
    "max" : 15,
  },
  {
    "name" : "Wrecking Team",
    "category" : "Special",
    "bigAndNasty" : 0,
    "deathFromAbove" : 0,
    "archerBroods" : 0,
  },
  {
    "name" : "Trolls",
    "category" : "Special",
    "bigAndNasty" : 0,
    "deathFromAbove" : 0,
    "archerBroods" : 0,
    "min" : 3,
    "max" : 9,
  },
  {
    "name" : "Goblin Artillery",
    "category" : "Special",
    "bigAndNasty" : 0,
    "deathFromAbove" : 1,
    "archerBroods" : 0,
  },
  {
    "name" : "Giant",
    "category" : "Special",
    "bigAndNasty" : 1,
    "deathFromAbove" : 0,
    "archerBroods" : 0,
  },
  {
    "name" : "Guardian Behemoth",
    "category" : "Special",
    "bigAndNasty" : 1,
    "deathFromAbove" : 0,
    "archerBroods" : 0,
  },
  {
    "name" : "Great Green Idol",
    "category" : "Special",
    "bigAndNasty" : 1,
    "deathFromAbove" : 0,
    "archerBroods" : 0,
  },
];

// SA
const SA = [
  {
    "name" : "anurarch archmage",
    "category" : "Characters",
    "saurianShooting" : 0,
  },
  {
    "name" : "caiman mentor",
    "category" : "Characters",
    "saurianShooting" : 0,
  },
  {
    "name" : "tegu veteran",
    "category" : "Characters",
    "saurianShooting" : 0,
  },
  {
    "name" : "skink veteran",
    "category" : "Characters",
    "saurianShooting" : 0,
  },
  {
    "name" : "tegu warriors",
    "category" : "Core",
    "saurianShooting" : 0,
    "min" : 15,
    "max" : 30,
  },
  {
    "name" : "skink warriors",
    "category" : "Core",
    "saurianShooting" : 0,
    "min" : 20,
    "max" : 40,
  },
  {
    "name" : "skink hunters",
    "category" : "Core",
    "saurianShooting" : 1,
    "min" : 12,
    "max" : 20,
  },
  {
    "name" : "caiman warriors",
    "category" : "Core",
    "saurianShooting" : 0,
    "min" : 4,
    "max" : 8,
  },
  {
    "name" : "tegu guards",
    "category" : "Special",
    "saurianShooting" : 0,
    "min" : 15,
    "max" : 25,
  },
  {
    "name" : "tegu mystics",
    "category" : "Special",
    "saurianShooting" : 0,
    "min" : 10,
    "max" : 20,
  },
  {
    "name" : "raptor pack",
    "category" : "Special",
    "saurianShooting" : 0,
    "min" : 6,
    "max" : 15,
  },
  {
    "name" : "raptor riders",
    "category" : "Special",
    "saurianShooting" : 0,
    "min" : 8,
    "max" : 15,
  },
  {
    "name" : "caiman elders",
    "category" : "Special",
    "saurianShooting" : 0,
    "min" : 3,
    "max" : 6,
  },
  {
    "name" : "thyroscutus herd",
    "category" : "Special",
    "saurianShooting" : 0,
    "min" : 1,
    "max" : 3,
  },
  {
    "name" : "rhamphodon riders",
    "category" : "Special",
    "saurianShooting" : 0,
    "min" : 3,
    "max" : 6,
  },
  {
    "name" : "saurian swarms",
    "category" : "Special",
    "saurianShooting" : 0,
    "min" : 3,
    "max" : 6,
  },
  {
    "name" : "skink guerrillas",
    "category" : "Special",
    "saurianShooting" : 0,
    "min" : 8,
    "max" : 15,
  },
  {
    "name" : "weapon beasts",
    "category" : "Special",
    "saurianShooting" : 2,
    "min" : 2,
    "max" : 4,
  },
  {
    "name" : "pteradon riders",
    "category" : "Special",
    "saurianShooting" : 0,
    "min" : 3,
    "max" : 6,
  },
  {
    "name" : "stygiosaur pack",
    "category" : "magna sauria",
    "saurianShooting" : 0,
    "min" : 2,
    "max" : 4,
  },
  {
    "name" : "carnosaur",
    "category" : "magna sauria",
    "saurianShooting" : 0,
  },
  {
    "name" : "taurosaur",
    "category" : "magna sauria",
    "saurianShooting" : 0,
  },
  {
    "name" : "titanopod",
    "category" : "magna sauria",
    "saurianShooting" : 0,
  },
];

// SE
const SE = [
  {
    "name" : "forest prince",
    "category" : "Characters",
    "sylvanShooting" : 0,
    "sylvanBeasts" : 0
  },
  {
    "name" : "chieftain",
    "category" : "Characters",
    "sylvanShooting" : 0,
    "sylvanBeasts" : 0
  },
  {
    "name" : "druid",
    "category" : "Characters",
    "sylvanShooting" : 0,
    "sylvanBeasts" : 0
  },
  {
    "name" : "dryad ancient",
    "category" : "Characters",
    "sylvanShooting" : 0,
    "sylvanBeasts" : 0
  },
  {
    "name" : "avatar of nature",
    "category" : "Characters",
    "sylvanShooting" : 0,
    "sylvanBeasts" : 2,
  },
  {
    "name" : "treefather ancient",
    "category" : "Characters",
    "sylvanShooting" : 0,
    "sylvanBeasts" : 1,
  },
  {
    "name" : "thicket shepherd",
    "category" : "Characters",
    "sylvanShooting" : 0,
    "sylvanBeasts" : 0,
  },
  {
    "name" : "forest guard",
    "category" : "Core",
    "sylvanShooting" : 0,
    "sylvanBeasts" : 0,
    "min" : 15,
    "max" : 35,
  },
  {
    "name" : "sylvan archers",
    "category" : "Core",
    "sylvanShooting" : 1,
    "sylvanBeasts" : 0,
    "min" : 10,
    "max" : 25,
  },
  {
    "name" : "heath riders",
    "category" : "Core",
    "sylvanShooting" : 0,
    "sylvanBeasts" : 0,
    "min" : 5,
    "max" : 15,
  },
  {
    "name" : "dryads",
    "category" : "Core",
    "sylvanShooting" : 0,
    "sylvanBeasts" : 0,
    "min" : 10,
    "max" : 25,
  },
  {
    "name" : "forest rangers",
    "category" : "Special",
    "sylvanShooting" : 0,
    "sylvanBeasts" : 0,
    "min" : 10,
    "max" : 25,
  },
  {
    "name" : "thicket beasts",
    "category" : "Special",
    "sylvanShooting" : 0,
    "sylvanBeasts" : 0,
    "min" : 4,
    "max" : 6,
  },
  {
    "name" : "forest eagles",
    "category" : "Special",
    "sylvanShooting" : 0,
    "sylvanBeasts" : 0,
    "min" : 1,
    "max" : 5,
  },
  {
    "name" : "blade dancers",
    "category" : "Special",
    "sylvanShooting" : 0,
    "sylvanBeasts" : 0,
    "min" : 7,
    "max" : 15,
  },
  {
    "name" : "treefather",
    "category" : "Special",
    "sylvanShooting" : 0,
    "sylvanBeasts" : 1,
  },
  {
    "name" : "wild huntsmen",
    "category" : "Special",
    "sylvanShooting" : 0,
    "sylvanBeasts" : 0,
    "min" : 5,
    "max" : 10,
  },
  {
    "name" : "kestrel knights",
    "category" : "Special",
    "sylvanShooting" : 0,
    "sylvanBeasts" : 0,
    "min" : 3,
    "max" : 4,
  },
  {
    "name" : "briar maidens",
    "category" : "unseen arrows",
    "sylvanShooting" : 0.5,
    "sylvanBeasts" : 0,
    "min" : 5,
    "max" : 10,
  },
  {
    "name" : "sylvan sentinels",
    "category" : "unseen arrows",
    "sylvanShooting" : 2,
    "sylvanBeasts" : 0,
    "min" : 5,
    "max" : 10,
  },
  {
    "name" : "pathfinders",
    "category" : "unseen arrows",
    "sylvanShooting" : 2,
    "sylvanBeasts" : 0,
    "min" : 5,
    "max" : 10,
  },
];

// UD
const UD = [
  {
    "name" : "pharaoh",
    "category" : "Characters",
    "aspisArrows" : 0,
    "deathFromAfar" : 0,
  },
  {
    "name" : "nomarch",
    "category" : "Characters",
    "aspisArrows" : 0,
    "deathFromAfar" : 0,
  },
  {
    "name" : "death cult hierarch",
    "category" : "Characters",
    "aspisArrows" : 0,
    "deathFromAfar" : 0,
  },
  {
    "name" : "skeleton warriors",
    "category" : "Core",
    "aspisArrows" : 0,
    "deathFromAfar" : 0,
    "min" : 20,
    "max" : 60,
  },
  {
    "name" : "skeleton archers",
    "category" : "Core",
    "aspisArrows" : 1,
    "deathFromAfar" : 0,
    "min" : 15,
    "max" : 30,
  },
  {
    "name" : "skeleton cavalry",
    "category" : "Core",
    "aspisArrows" : 0,
    "deathFromAfar" : 0,
    "min" : 10,
    "max" : 24,
  },
  {
    "name" : "skeleton scouts",
    "category" : "Core",
    "aspisArrows" : 1,
    "deathFromAfar" : 0,
    "min" : 5,
    "max" : 10,
  },
  {
    "name" : "skeleton chariots",
    "category" : "Core",
    "aspisArrows" : 0,
    "deathFromAfar" : 0,
    "min" : 3,
    "max" : 7,
  },
  {
    "name" : "necropolis guard",
    "category" : "Special",
    "aspisArrows" : 0,
    "deathFromAfar" : 0,
    "min" : 15,
    "max" : 40,
  },
  {
    "name" : "tomb cataphracts",
    "category" : "Special",
    "aspisArrows" : 0,
    "deathFromAfar" : 0,
    "min" : 3,
    "max" : 5,
  },
  {
    "name" : "shabtis",
    "category" : "Special",
    "aspisArrows" : 0,
    "deathFromAfar" : 0,
    "min" : 3,
    "max" : 8,
  },
  {
    "name" : "shabti archers",
    "category" : "Special",
    "aspisArrows" : 2,
    "deathFromAfar" : 0,
    "min" : 3,
    "max" : 6,
  },
  {
    "name" : "great vultures",
    "category" : "Special",
    "aspisArrows" : 0,
    "deathFromAfar" : 0,
    "min" : 3,
    "max" : 9,
  },
  {
    "name" : "scarab swarms",
    "category" : "Special",
    "aspisArrows" : 0,
    "deathFromAfar" : 0,
    "min" : 3,
    "max" : 6,
  },
  {
    "name" : "sand stalkers",
    "category" : "Special",
    "aspisArrows" : 0,
    "deathFromAfar" : 0,
    "min" : 3,
    "max" : 4,
  },
  {
    "name" : "casket of phatep",
    "category" : "Special",
    "aspisArrows" : 0,
    "deathFromAfar" : 0,
  },
  {
    "name" : "charnel catapult",
    "category" : "Special",
    "aspisArrows" : 0,
    "deathFromAfar" : 1,
  },
  {
    "name" : "sand scorpion",
    "category" : "entombed",
    "aspisArrows" : 0,
    "deathFromAfar" : 0,
  },
  {
    "name" : "battle sphinx",
    "category" : "mason's menagerie",
    "aspisArrows" : 0,
    "deathFromAfar" : 0,
  },
  {
    "name" : "dread sphinx",
    "category" : "mason's menagerie",
    "aspisArrows" : 0,
    "deathFromAfar" : 0,
  },
  {
    "name" : "tomb reapers",
    "category" : "mason's menagerie",
    "aspisArrows" : 0,
    "deathFromAfar" : 0,
    "min" : 2,
    "max" : 4,
  },
  {
    "name" : "colossus",
    "category" : "mason's menagerie",
    "aspisArrows" : 0,
    "deathFromAfar" : 0,
  },
];

// VC
const VC = [
  {
    "name" : "vampire count",
    "category" : "Characters",
  },
  {
    "name" : "vampire courtier",
    "category" : "Characters",
  },
  {
    "name" : "necromancer",
    "category" : "Characters",
  },
  {
    "name" : "barrow king",
    "category" : "Characters",
  },
  {
    "name" : "banshee",
    "category" : "Characters",
  },
  {
    "name" : "zombies",
    "category" : "Core",
    "min" : 20,
    "max" : 80,
  },
  {
    "name" : "skeletons",
    "category" : "Core",
    "min" : 20,
    "max" : 60,
  },
  {
    "name" : "ghouls",
    "category" : "Core",
    "min" : 15,
    "max" : 40,
  },
  {
    "name" : "bat swarms",
    "category" : "Core",
    "min" : 3,
    "max" : 6,
  },
  {
    "name" : "dire wolves",
    "category" : "Core",
    "min" : 8,
    "max" : 15,
  },
  {
    "name" : "great bats",
    "category" : "Special",
    "min" : 2,
    "max" : 9,
  },
  {
    "name" : "ghasts",
    "category" : "Special",
    "min" : 3,
    "max" : 8,
  },
  {
    "name" : "barrow guard",
    "category" : "Special",
    "min" : 15,
    "max" : 40,
  },
  {
    "name" : "barrow knights",
    "category" : "Special",
    "min" : 5,
    "max" : 15,
  },
  {
    "name" : "cadaver wagon",
    "category" : "Special",
  },
  {
    "name" : "dark coach",
    "category" : "Special",
  },
  {
    "name" : "court of the damned",
    "category" : "Special",
  },
  {
    "name" : "altar of undeath",
    "category" : "Special",
  },
  {
    "name" : "phantom hosts",
    "category" : "the suffering",
    "min" : 3,
    "max" : 6,
  },
  {
    "name" : "wraiths",
    "category" : "the suffering",
    "min" : 5,
    "max" : 10,
  },
  {
    "name" : "spectral hunters",
    "category" : "the suffering",
    "min" : 5,
    "max" : 10,
  },
  {
    "name" : "vampire knights",
    "category" : "swift death",
    "min" : 3,
    "max" : 6,
  },
  {
    "name" : "vampire spawn",
    "category" : "swift death",
    "min" : 3,
    "max" : 6,
  },
  {
    "name" : "varkolak",
    "category" : "swift death",
  },
  {
    "name" : "winged reapers",
    "category" : "swift death",
    "min" : 2,
    "max" : 4,
  },
  {
    "name" : "shrieking horror",
    "category" : "swift death",
  },
];

// VS
const VS = [
  {
    "name" : "ruinous dictator",
    "category" : "Characters",
    "experimentalWeapon" : 0,
  },
  {
    "name" : "vermin senator",
    "category" : "Characters",
    "experimentalWeapon" : 0
  },
  {
    "name" : "bloodfur legate",
    "category" : "Characters",
    "experimentalWeapon" : 0
  },
  {
    "name" : "house prefect",
    "category" : "Characters",
    "experimentalWeapon" : 0
  },
  {
    "name" : "swarm priest",
    "category" : "Characters",
    "experimentalWeapon" : 0
  },
  {
    "name" : "duskblade assassin",
    "category" : "Characters",
    "experimentalWeapon" : 0
  },
  {
    "name" : "vermin slingers",
    "category" : "Core",
    "experimentalWeapon" : 0,
    "min" : 20,
    "max" : 30,
  },
  {
    "name" : "vermin legionaries",
    "category" : "Core",
    "experimentalWeapon" : 0,
    "min" : 25,
    "max" : 60,
  },
  {
    "name" : "blackfur veterans",
    "category" : "Core",
    "experimentalWeapon" : 0,
    "min" : 20,
    "max" : 40,
  },
  {
    "name" : "vermin slaves",
    "category" : "Core",
    "experimentalWeapon" : 0,
    "min" : 30,
    "max" : 60,
  },
  {
    "name" : "plague cultists",
    "category" : "Core",
    "experimentalWeapon" : 0,
    "min" : 20,
    "max" : 40,
  },
  {
    "name" : "plague disciples",
    "category" : "Core",
    "experimentalWeapon" : 0,
    "min" : 15,
    "max" : 40,
  },
  {
    "name" : "giant rats",
    "category" : "Core",
    "experimentalWeapon" : 0,
    "min" : 10,
    "max" : 30,
  },
  {
    "name" : "fire rats",
    "category" : "Special",
    "experimentalWeapon" : 0,
    "min" : 10,
    "max" : 20,
  },
  {
    "name" : "bloodfur praetorians",
    "category" : "Special",
    "experimentalWeapon" : 0,
    "min" : 20,
    "max" : 40,
  },
  {
    "name" : "rat swarm",
    "category" : "Special",
    "experimentalWeapon" : 0,
    "min" : 3,
    "max" : 6,
  },
  {
    "name" : "vermin brutes",
    "category" : "Special",
    "experimentalWeapon" : 0,
    "bruteForce" : 1,
    "min" : 6,
    "max" : 12,
  },
  {
    "name" : "gladiator brutes",
    "category" : "Special",
    "experimentalWeapon" : 0,
    "bruteForce" : 1,
    "min" : 3,
    "max" : 6,
  },
  {
    "name" : "legionary drill team",
    "category" : "Special",
    "experimentalWeapon" : 0
  },
  {
    "name" : "shadowfur stalkers",
    "category" : "Special",
    "experimentalWeapon" : 0,
    "min" : 10,
    "max" : 15,
  },
  {
    "name" : "doomspark device",
    "category" : "Special",
    "experimentalWeapon" : 0
  },
  {
    "name" : "thunder brutes",
    "category" : "Special",
    "experimentalWeapon" : 0,
    "bruteForce" : 1,
    "min" : 3,
    "max" : 6,
  },
  {
    "name" : "ignifier grenadiers",
    "category" : "Special",
    "experimentalWeapon" : 0
  },
  {
    "name" : "experimental weapon teams",
    "category" : "Special",
    "experimentalWeapon" : 1,
    "min" : 3,
    "max" : 6,
  },
  {
    "name" : "vermin artillery",
    "category" : "Special",
    "experimentalWeapon" : 0
  },
  {
    "name" : "stygian earthbreaker",
    "category" : "bread and games",
    "experimentalWeapon" : 0
  },
  {
    "name" : "dreadmill chariots",
    "category" : "bread and games",
    "experimentalWeapon" : 0,
    "min" : 1,
    "max" : 3,
  },
  {
    "name" : "arena beast",
    "category" : "bread and games",
    "experimentalWeapon" : 0
  },

];

// WDG
const WDG = [
  {
    "name" : "Exalted Herald",
    "category" : "Characters",
    "legendaryBeast" : 3,
  },
  {
    "name" : "Chosen Lord",
    "category" : "Characters",
    "legendaryBeast" : 0
  },
  {
    "name" : "Doomlord",
    "category" : "Characters",
    "legendaryBeast" : 0
  },
  {
    "name" : "Sorcerer",
    "category" : "Characters",
    "legendaryBeast" : 0
  },
  {
    "name" : "Barbarian Chief",
    "category" : "Characters",
    "legendaryBeast" : 0
  },
  {
    "name" : "Feldrak ancestor",
    "category" : "Characters",
    "legendaryBeast" : 2
  },
  {
    "name" : "Warriors",
    "category" : "Core",
    "legendaryBeast" : 0,
    "min" : 10,
    "max" : 25,
  },
  {
    "name" : "Fallen",
    "category" : "Core",
    "legendaryBeast" : 0,
    "min" : 5,
    "max" : 15,

  },
  {
    "name" : "Barbarians",
    "category" : "Core",
    "legendaryBeast" : 0,
    "min" : 15,
    "max" : 40,

  },
  {
    "name" : "Barbarian Horsemen",
    "category" : "Core",
    "legendaryBeast" : 0,
    "min" : 5,
    "max" : 15,

  },
  {
    "name" : "Warhounds",
    "category" : "Special",
    "conditionalCore" : 8,
    "legendaryBeast" : 0,
    "min" : 5,
    "max" : 15,

  },
  {
    "name" : "Warrior Knights",
    "category" : "Special",
    "legendaryBeast" : 0,
    "min" : 5,
    "max" : 10,

  },
  {
    "name" : "Warrior Chariot",
    "category" : "Special",
    "legendaryBeast" : 0
  },
  {
    "name" : "Chosen",
    "category" : "Special",
    "legendaryBeast" : 0,
    "min" : 5,
    "max" : 10,

  },
  {
    "name" : "Chosen Knights",
    "category" : "Special",
    "legendaryBeast" : 0,
    "min" : 3,
    "max" : 4,

  },
  {
    "name" : "Chosen Chariot",
    "category" : "Special",
    "legendaryBeast" : 0
  },
  {
    "name" : "Chimera",
    "category" : "Special",
    "legendaryBeast" : 1
  },
  {
    "name" : "Wretched Ones",
    "category" : "Special",
    "legendaryBeast" : 0,
    "min" : 1,
    "max" : 6,

  },
  {
    "name" : "Forsworn",
    "category" : "Special",
    "legendaryBeast" : 0,
    "min" : 3,
    "max" : 9,

  },
  {
    "name" : "Feldraks",
    "category" : "Special",
    "legendaryBeast" : 0,
    "min" : 3,
    "max" : 5,
  },
  {
    "name" : "Battleshrine",
    "category" : "Special",
    "legendaryBeast" : 0
  },
  {
    "name" : "Flayers",
    "category" : "Special",
    "legendaryBeast" : 0,
    "min" : 5,
    "max" : 10,
  },
  {
    "name" : "Hellmaw",
    "category" : "Special",
    "legendaryBeast" : 0
  },
  {
    "name" : "Forsaken One",
    "category" : "Special",
    "legendaryBeast" : 2
  },
  {
    "name" : "Marauding Giant",
    "category" : "Special",
    "legendaryBeast" : 1
  },
  {
    "name" : "Feldrak Elder",
    "category" : "Special",
    "legendaryBeast" : 2
  },

];

// exports
module.exports = {
  BH,
  DE,
  DH,
  DL,
  EoS,
  HE,
  ID,
  KoE,
  OK,
  OnG,
  SA,
  SE,
  UD,
  VC,
  VS,
  WDG
};
